// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesmetrics

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInboxesMetricsRoot(parent *cobra.Command) error {
	var InboxesMetricsCmd = &cobra.Command{
		Use:   "inboxes-metrics",
		Short: "Operations for inboxes-metrics",
		Long:  "Operations for inboxes-metrics",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ime"},
	}

	if err := initInboxesMetricsQueryCmd(InboxesMetricsCmd); err != nil {
		return err
	}

	parent.AddCommand(InboxesMetricsCmd)
	return nil
}
