// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var webhooksCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "url", Shorthand: "u", FieldPath: "URL", Kind: flagutil.FlagKindString, Required: true, Description: "URL of webhook endpoint. [required]"},
	{FlagName: "event-types", Shorthand: "e", FieldPath: "EventTypes", Kind: flagutil.FlagKindStringArray, Required: true, Description: "Event types for which to send events. [required]"},
	{FlagName: "pod-ids", Shorthand: "p", FieldPath: "PodIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Pods for which to send events. Maximum 10 per webhook."},
	{FlagName: "inbox-ids", Shorthand: "i", FieldPath: "InboxIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Inboxes for which to send events. Maximum 10 per webhook."},
	{FlagName: "client-id", Shorthand: "c", FieldPath: "ClientID", Kind: flagutil.FlagKindString, Optional: true, Description: "Client ID of webhook."},
}

// initWebhooksCreateCmd initializes the webhooks-create command.
func initWebhooksCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create Webhook",
		Long:    "**CLI:**\n```bash\nagentmail webhooks create --url https://example.com/webhook --event-type message.received\n```",
		Example: "  cli webhooks create --url https://odd-zebra.org/ --event-types '[\"message.rejected\"]'",
		RunE:    runWebhooksCreateCmd,
	}
	flagutil.RegisterFlags(cmd, webhooksCreateCmdMeta)
	if err := flagutil.ValidateMeta[components.WebhooksCreateWebhookRequest](webhooksCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for webhooks-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runWebhooksCreateCmd executes the webhooks-create command.
func runWebhooksCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, webhooksCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, webhooksCreateCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.WebhooksCreateWebhookRequest](cmd, webhooksCreateCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.WebhooksCreateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.WebhooksCreateServerList)-1)
		}
		serverURL := operations.WebhooksCreateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Webhooks.WebhooksCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
