// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var webhooksListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "page-token", Shorthand: "p", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "ascending", Shorthand: "a", FieldPath: "Ascending", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initWebhooksListCmd initializes the webhooks-list command.
func initWebhooksListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Webhooks",
		Long:    "**CLI:**\n```bash\nagentmail webhooks list\n```",
		Example: "  cli webhooks list",
		RunE:    runWebhooksListCmd,
	}
	flagutil.RegisterFlags(cmd, webhooksListCmdMeta)
	if err := flagutil.ValidateMeta[operations.WebhooksListRequest](webhooksListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for webhooks-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runWebhooksListCmd executes the webhooks-list command.
func runWebhooksListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, webhooksListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, webhooksListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.WebhooksListRequest](cmd, webhooksListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.WebhooksListServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.WebhooksListServerList)-1)
		}
		serverURL := operations.WebhooksListServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Webhooks.WebhooksList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
