// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var webhooksUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "webhook-id", Shorthand: "w", FieldPath: "WebhookID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "add-inbox-ids", FieldPath: "Body.AddInboxIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Inboxes for which to send events. Maximum 10 per webhook."},
	{FlagName: "remove-inbox-ids", FieldPath: "Body.RemoveInboxIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Inboxes for which to send events. Maximum 10 per webhook."},
	{FlagName: "add-pod-ids", FieldPath: "Body.AddPodIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Pods for which to send events. Maximum 10 per webhook."},
	{FlagName: "remove-pod-ids", FieldPath: "Body.RemovePodIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Pods for which to send events. Maximum 10 per webhook."},
}

// initWebhooksUpdateCmd initializes the webhooks-update command.
func initWebhooksUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update Webhook",
		Long:    "**CLI:**\n```bash\nagentmail webhooks update --webhook-id <webhook_id> --add-inbox-id <inbox_id>\n```",
		Example: "  cli webhooks update --webhook-id <id>",
		RunE:    runWebhooksUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, webhooksUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.WebhooksUpdateRequest](webhooksUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for webhooks-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runWebhooksUpdateCmd executes the webhooks-update command.
func runWebhooksUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, webhooksUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, webhooksUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.WebhooksUpdateRequest](cmd, webhooksUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.WebhooksUpdateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.WebhooksUpdateServerList)-1)
		}
		serverURL := operations.WebhooksUpdateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Webhooks.WebhooksUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
