// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var webhooksGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "webhook-id", Shorthand: "w", FieldPath: "WebhookID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initWebhooksGetCmd initializes the webhooks-get command.
func initWebhooksGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Webhook",
		Long:    "**CLI:**\n```bash\nagentmail webhooks get --webhook-id <webhook_id>\n```",
		Example: "  agentmail webhooks get --webhook-id <id>",
		RunE:    runWebhooksGetCmd,
	}
	flagutil.RegisterFlags(cmd, webhooksGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.WebhooksGetRequest](webhooksGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for webhooks-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runWebhooksGetCmd executes the webhooks-get command.
func runWebhooksGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, webhooksGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, webhooksGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.WebhooksGetRequest](cmd, webhooksGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.WebhooksGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.WebhooksGetServerList)-1)
		}
		serverURL := operations.WebhooksGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Webhooks.WebhooksGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
