// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package podsinboxes

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var podsInboxesGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pod-id", Shorthand: "p", FieldPath: "PodID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initPodsInboxesGetCmd initializes the pods-inboxes-get command.
func initPodsInboxesGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Inbox",
		Long:    "**CLI:**\n```bash\nagentmail pods:inboxes get --pod-id <pod_id> --inbox-id <inbox_id>\n```",
		Example: "  cli pods-inboxes get --pod-id <id> --inbox-id <id>",
		RunE:    runPodsInboxesGetCmd,
	}
	flagutil.RegisterFlags(cmd, podsInboxesGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.PodsInboxesGetRequest](podsInboxesGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pods-inboxes-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPodsInboxesGetCmd executes the pods-inboxes-get command.
func runPodsInboxesGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, podsInboxesGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, podsInboxesGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PodsInboxesGetRequest](cmd, podsInboxesGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.PodsInboxesGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.PodsInboxesGetServerList)-1)
		}
		serverURL := operations.PodsInboxesGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PodsInboxes.PodsInboxesGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
