// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var AgentVerifyServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type AgentVerifyResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	AgentVerifyResponse *components.AgentVerifyResponse
}

func (a AgentVerifyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentVerifyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentVerifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AgentVerifyResponse) GetAgentVerifyResponse() *components.AgentVerifyResponse {
	if a == nil {
		return nil
	}
	return a.AgentVerifyResponse
}
