// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var AgentSignUpServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type AgentSignUpResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	AgentSignupResponse *components.AgentSignupResponse
}

func (a AgentSignUpResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentSignUpResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentSignUpResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AgentSignUpResponse) GetAgentSignupResponse() *components.AgentSignupResponse {
	if a == nil {
		return nil
	}
	return a.AgentSignupResponse
}
