// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var APIKeysDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type APIKeysDeleteRequest struct {
	APIKeyID string `pathParam:"style=simple,explode=false,name=api_key_id"`
}

func (a *APIKeysDeleteRequest) GetAPIKeyID() string {
	if a == nil {
		return ""
	}
	return a.APIKeyID
}

type APIKeysDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (a *APIKeysDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}
