// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var DomainsGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DomainsGetRequest struct {
	DomainID string `pathParam:"style=simple,explode=false,name=domain_id"`
}

func (d *DomainsGetRequest) GetDomainID() string {
	if d == nil {
		return ""
	}
	return d.DomainID
}

type DomainsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Domain   *components.Domain
}

func (d DomainsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DomainsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DomainsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DomainsGetResponse) GetDomain() *components.Domain {
	if d == nil {
		return nil
	}
	return d.Domain
}
