// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var DomainsDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DomainsDeleteRequest struct {
	DomainID string `pathParam:"style=simple,explode=false,name=domain_id"`
}

func (d *DomainsDeleteRequest) GetDomainID() string {
	if d == nil {
		return ""
	}
	return d.DomainID
}

type DomainsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DomainsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
