// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var DomainsUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DomainsUpdateRequest struct {
	DomainID string                         `pathParam:"style=simple,explode=false,name=domain_id"`
	Body     components.UpdateDomainRequest `request:"mediaType=application/json"`
}

func (d *DomainsUpdateRequest) GetDomainID() string {
	if d == nil {
		return ""
	}
	return d.DomainID
}

func (d *DomainsUpdateRequest) GetBody() components.UpdateDomainRequest {
	if d == nil {
		return components.UpdateDomainRequest{}
	}
	return d.Body
}

type DomainsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Domain   *components.Domain
}

func (d DomainsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DomainsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DomainsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DomainsUpdateResponse) GetDomain() *components.Domain {
	if d == nil {
		return nil
	}
	return d.Domain
}
