// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var DomainsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DomainsListRequest struct {
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (d *DomainsListRequest) GetLimit() *int64 {
	if d == nil {
		return nil
	}
	return d.Limit
}

func (d *DomainsListRequest) GetPageToken() *string {
	if d == nil {
		return nil
	}
	return d.PageToken
}

func (d *DomainsListRequest) GetAscending() *bool {
	if d == nil {
		return nil
	}
	return d.Ascending
}

type DomainsListResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	ListDomainsResponse *components.ListDomainsResponse
}

func (d DomainsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DomainsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DomainsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DomainsListResponse) GetListDomainsResponse() *components.ListDomainsResponse {
	if d == nil {
		return nil
	}
	return d.ListDomainsResponse
}
