// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"io"
)

var DomainsGetZoneFileServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DomainsGetZoneFileRequest struct {
	DomainID string `pathParam:"style=simple,explode=false,name=domain_id"`
}

func (d *DomainsGetZoneFileRequest) GetDomainID() string {
	if d == nil {
		return ""
	}
	return d.DomainID
}

type DomainsGetZoneFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (d *DomainsGetZoneFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DomainsGetZoneFileResponse) GetResponseStream() io.ReadCloser {
	if d == nil {
		return nil
	}
	return d.ResponseStream
}
