// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

var DraftsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DraftsListRequest struct {
	Limit     *int64     `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string    `queryParam:"style=form,explode=true,name=page_token"`
	Labels    []string   `queryParam:"style=form,explode=true,name=labels"`
	Before    *time.Time `queryParam:"style=form,explode=true,name=before"`
	After     *time.Time `queryParam:"style=form,explode=true,name=after"`
	Ascending *bool      `queryParam:"style=form,explode=true,name=ascending"`
}

func (d DraftsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DraftsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DraftsListRequest) GetLimit() *int64 {
	if d == nil {
		return nil
	}
	return d.Limit
}

func (d *DraftsListRequest) GetPageToken() *string {
	if d == nil {
		return nil
	}
	return d.PageToken
}

func (d *DraftsListRequest) GetLabels() []string {
	if d == nil {
		return nil
	}
	return d.Labels
}

func (d *DraftsListRequest) GetBefore() *time.Time {
	if d == nil {
		return nil
	}
	return d.Before
}

func (d *DraftsListRequest) GetAfter() *time.Time {
	if d == nil {
		return nil
	}
	return d.After
}

func (d *DraftsListRequest) GetAscending() *bool {
	if d == nil {
		return nil
	}
	return d.Ascending
}

type DraftsListResponse struct {
	HTTPMeta           components.HTTPMetadata `json:"-"`
	ListDraftsResponse *components.ListDraftsResponse
}

func (d DraftsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DraftsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DraftsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DraftsListResponse) GetListDraftsResponse() *components.ListDraftsResponse {
	if d == nil {
		return nil
	}
	return d.ListDraftsResponse
}
