// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var DraftsGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type DraftsGetRequest struct {
	DraftID string `pathParam:"style=simple,explode=false,name=draft_id"`
}

func (d *DraftsGetRequest) GetDraftID() string {
	if d == nil {
		return ""
	}
	return d.DraftID
}

type DraftsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Draft    *components.Draft
}

func (d DraftsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DraftsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DraftsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DraftsGetResponse) GetDraft() *components.Draft {
	if d == nil {
		return nil
	}
	return d.Draft
}
