// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesDraftsGetAttachmentServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesDraftsGetAttachmentRequest struct {
	InboxID      string `pathParam:"style=simple,explode=false,name=inbox_id"`
	DraftID      string `pathParam:"style=simple,explode=false,name=draft_id"`
	AttachmentID string `pathParam:"style=simple,explode=false,name=attachment_id"`
}

func (i *InboxesDraftsGetAttachmentRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesDraftsGetAttachmentRequest) GetDraftID() string {
	if i == nil {
		return ""
	}
	return i.DraftID
}

func (i *InboxesDraftsGetAttachmentRequest) GetAttachmentID() string {
	if i == nil {
		return ""
	}
	return i.AttachmentID
}

type InboxesDraftsGetAttachmentResponse struct {
	HTTPMeta           components.HTTPMetadata `json:"-"`
	AttachmentResponse *components.AttachmentResponse
}

func (i InboxesDraftsGetAttachmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesDraftsGetAttachmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesDraftsGetAttachmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesDraftsGetAttachmentResponse) GetAttachmentResponse() *components.AttachmentResponse {
	if i == nil {
		return nil
	}
	return i.AttachmentResponse
}
