// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesMessagesReplyServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesMessagesReplyRequest struct {
	InboxID   string                           `pathParam:"style=simple,explode=false,name=inbox_id"`
	MessageID string                           `pathParam:"style=simple,explode=false,name=message_id"`
	Body      components.ReplyToMessageRequest `request:"mediaType=application/json"`
}

func (i *InboxesMessagesReplyRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesMessagesReplyRequest) GetMessageID() string {
	if i == nil {
		return ""
	}
	return i.MessageID
}

func (i *InboxesMessagesReplyRequest) GetBody() components.ReplyToMessageRequest {
	if i == nil {
		return components.ReplyToMessageRequest{}
	}
	return i.Body
}

type InboxesMessagesReplyResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	SendMessageResponse *components.SendMessageResponse
}

func (i InboxesMessagesReplyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMessagesReplyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMessagesReplyResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesMessagesReplyResponse) GetSendMessageResponse() *components.SendMessageResponse {
	if i == nil {
		return nil
	}
	return i.SendMessageResponse
}
