// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var InboxesDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesDeleteRequest struct {
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
}

func (i *InboxesDeleteRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

type InboxesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InboxesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
