// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesListsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesListsListRequest struct {
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
	// Direction of list entry.
	Direction components.Direction `pathParam:"style=simple,explode=false,name=direction"`
	// Type of list entry.
	Type      components.ListType `pathParam:"style=simple,explode=false,name=type"`
	Limit     *int64              `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string             `queryParam:"style=form,explode=true,name=page_token"`
}

func (i *InboxesListsListRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesListsListRequest) GetDirection() components.Direction {
	if i == nil {
		return components.Direction("")
	}
	return i.Direction
}

func (i *InboxesListsListRequest) GetType() components.ListType {
	if i == nil {
		return components.ListType("")
	}
	return i.Type
}

func (i *InboxesListsListRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesListsListRequest) GetPageToken() *string {
	if i == nil {
		return nil
	}
	return i.PageToken
}

type InboxesListsListResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	PodListListEntriesResponse *components.PodListListEntriesResponse
}

func (i InboxesListsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesListsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesListsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesListsListResponse) GetPodListListEntriesResponse() *components.PodListListEntriesResponse {
	if i == nil {
		return nil
	}
	return i.PodListListEntriesResponse
}
