// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesMessagesForwardServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesMessagesForwardRequest struct {
	InboxID   string                        `pathParam:"style=simple,explode=false,name=inbox_id"`
	MessageID string                        `pathParam:"style=simple,explode=false,name=message_id"`
	Body      components.SendMessageRequest `request:"mediaType=application/json"`
}

func (i *InboxesMessagesForwardRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesMessagesForwardRequest) GetMessageID() string {
	if i == nil {
		return ""
	}
	return i.MessageID
}

func (i *InboxesMessagesForwardRequest) GetBody() components.SendMessageRequest {
	if i == nil {
		return components.SendMessageRequest{}
	}
	return i.Body
}

type InboxesMessagesForwardResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	SendMessageResponse *components.SendMessageResponse
}

func (i InboxesMessagesForwardResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMessagesForwardResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMessagesForwardResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesMessagesForwardResponse) GetSendMessageResponse() *components.SendMessageResponse {
	if i == nil {
		return nil
	}
	return i.SendMessageResponse
}
