// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

var InboxesMessagesListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesMessagesListRequest struct {
	InboxID        string     `pathParam:"style=simple,explode=false,name=inbox_id"`
	Limit          *int64     `queryParam:"style=form,explode=true,name=limit"`
	PageToken      *string    `queryParam:"style=form,explode=true,name=page_token"`
	Labels         []string   `queryParam:"style=form,explode=true,name=labels"`
	Before         *time.Time `queryParam:"style=form,explode=true,name=before"`
	After          *time.Time `queryParam:"style=form,explode=true,name=after"`
	Ascending      *bool      `queryParam:"style=form,explode=true,name=ascending"`
	IncludeSpam    *bool      `queryParam:"style=form,explode=true,name=include_spam"`
	IncludeBlocked *bool      `queryParam:"style=form,explode=true,name=include_blocked"`
	IncludeTrash   *bool      `queryParam:"style=form,explode=true,name=include_trash"`
}

func (i InboxesMessagesListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMessagesListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMessagesListRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesMessagesListRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesMessagesListRequest) GetPageToken() *string {
	if i == nil {
		return nil
	}
	return i.PageToken
}

func (i *InboxesMessagesListRequest) GetLabels() []string {
	if i == nil {
		return nil
	}
	return i.Labels
}

func (i *InboxesMessagesListRequest) GetBefore() *time.Time {
	if i == nil {
		return nil
	}
	return i.Before
}

func (i *InboxesMessagesListRequest) GetAfter() *time.Time {
	if i == nil {
		return nil
	}
	return i.After
}

func (i *InboxesMessagesListRequest) GetAscending() *bool {
	if i == nil {
		return nil
	}
	return i.Ascending
}

func (i *InboxesMessagesListRequest) GetIncludeSpam() *bool {
	if i == nil {
		return nil
	}
	return i.IncludeSpam
}

func (i *InboxesMessagesListRequest) GetIncludeBlocked() *bool {
	if i == nil {
		return nil
	}
	return i.IncludeBlocked
}

func (i *InboxesMessagesListRequest) GetIncludeTrash() *bool {
	if i == nil {
		return nil
	}
	return i.IncludeTrash
}

type InboxesMessagesListResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	ListMessagesResponse *components.ListMessagesResponse
}

func (i InboxesMessagesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMessagesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMessagesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesMessagesListResponse) GetListMessagesResponse() *components.ListMessagesResponse {
	if i == nil {
		return nil
	}
	return i.ListMessagesResponse
}
