// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

var InboxesMetricsQueryServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesMetricsQueryRequest struct {
	InboxID    string                       `pathParam:"style=simple,explode=false,name=inbox_id"`
	EventTypes []components.MetricEventType `queryParam:"style=form,explode=true,name=event_types"`
	Start      *time.Time                   `queryParam:"style=form,explode=true,name=start"`
	End        *time.Time                   `queryParam:"style=form,explode=true,name=end"`
	Period     *string                      `queryParam:"style=form,explode=true,name=period"`
	Limit      *int64                       `queryParam:"style=form,explode=true,name=limit"`
	Descending *bool                        `queryParam:"style=form,explode=true,name=descending"`
}

func (i InboxesMetricsQueryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMetricsQueryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMetricsQueryRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesMetricsQueryRequest) GetEventTypes() []components.MetricEventType {
	if i == nil {
		return nil
	}
	return i.EventTypes
}

func (i *InboxesMetricsQueryRequest) GetStart() *time.Time {
	if i == nil {
		return nil
	}
	return i.Start
}

func (i *InboxesMetricsQueryRequest) GetEnd() *time.Time {
	if i == nil {
		return nil
	}
	return i.End
}

func (i *InboxesMetricsQueryRequest) GetPeriod() *string {
	if i == nil {
		return nil
	}
	return i.Period
}

func (i *InboxesMetricsQueryRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesMetricsQueryRequest) GetDescending() *bool {
	if i == nil {
		return nil
	}
	return i.Descending
}

type InboxesMetricsQueryResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	QueryMetricsResponse map[string][]components.MetricBucket
}

func (i InboxesMetricsQueryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMetricsQueryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMetricsQueryResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesMetricsQueryResponse) GetQueryMetricsResponse() map[string][]components.MetricBucket {
	if i == nil {
		return nil
	}
	return i.QueryMetricsResponse
}
