// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesGetRequest struct {
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
}

func (i *InboxesGetRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

type InboxesGetResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	InboxesInbox *components.InboxesInbox
}

func (i InboxesGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesGetResponse) GetInboxesInbox() *components.InboxesInbox {
	if i == nil {
		return nil
	}
	return i.InboxesInbox
}
