// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesListsGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesListsGetRequest struct {
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
	// Direction of list entry.
	Direction components.Direction `pathParam:"style=simple,explode=false,name=direction"`
	// Type of list entry.
	Type components.ListType `pathParam:"style=simple,explode=false,name=type"`
	// Email address or domain.
	Entry string `pathParam:"style=simple,explode=false,name=entry"`
}

func (i *InboxesListsGetRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesListsGetRequest) GetDirection() components.Direction {
	if i == nil {
		return components.Direction("")
	}
	return i.Direction
}

func (i *InboxesListsGetRequest) GetType() components.ListType {
	if i == nil {
		return components.ListType("")
	}
	return i.Type
}

func (i *InboxesListsGetRequest) GetEntry() string {
	if i == nil {
		return ""
	}
	return i.Entry
}

type InboxesListsGetResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	PodListEntry *components.PodListEntry
}

func (i InboxesListsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesListsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesListsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesListsGetResponse) GetPodListEntry() *components.PodListEntry {
	if i == nil {
		return nil
	}
	return i.PodListEntry
}
