// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesDraftsCreateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesDraftsCreateRequest struct {
	InboxID string                        `pathParam:"style=simple,explode=false,name=inbox_id"`
	Body    components.CreateDraftRequest `request:"mediaType=application/json"`
}

func (i *InboxesDraftsCreateRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesDraftsCreateRequest) GetBody() components.CreateDraftRequest {
	if i == nil {
		return components.CreateDraftRequest{}
	}
	return i.Body
}

type InboxesDraftsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Draft    *components.Draft
}

func (i InboxesDraftsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesDraftsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesDraftsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesDraftsCreateResponse) GetDraft() *components.Draft {
	if i == nil {
		return nil
	}
	return i.Draft
}
