// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesMessagesUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesMessagesUpdateRequest struct {
	InboxID   string                          `pathParam:"style=simple,explode=false,name=inbox_id"`
	MessageID string                          `pathParam:"style=simple,explode=false,name=message_id"`
	Body      components.UpdateMessageRequest `request:"mediaType=application/json"`
}

func (i *InboxesMessagesUpdateRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesMessagesUpdateRequest) GetMessageID() string {
	if i == nil {
		return ""
	}
	return i.MessageID
}

func (i *InboxesMessagesUpdateRequest) GetBody() components.UpdateMessageRequest {
	if i == nil {
		return components.UpdateMessageRequest{}
	}
	return i.Body
}

type InboxesMessagesUpdateResponse struct {
	HTTPMeta              components.HTTPMetadata `json:"-"`
	UpdateMessageResponse *components.UpdateMessageResponse
}

func (i InboxesMessagesUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMessagesUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMessagesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesMessagesUpdateResponse) GetUpdateMessageResponse() *components.UpdateMessageResponse {
	if i == nil {
		return nil
	}
	return i.UpdateMessageResponse
}
