// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesEventsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesEventsListRequest struct {
	InboxID   string  `pathParam:"style=simple,explode=false,name=inbox_id"`
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (i *InboxesEventsListRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesEventsListRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesEventsListRequest) GetPageToken() *string {
	if i == nil {
		return nil
	}
	return i.PageToken
}

func (i *InboxesEventsListRequest) GetAscending() *bool {
	if i == nil {
		return nil
	}
	return i.Ascending
}

type InboxesEventsListResponse struct {
	HTTPMeta                components.HTTPMetadata `json:"-"`
	ListInboxEventsResponse *components.ListInboxEventsResponse
}

func (i InboxesEventsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesEventsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesEventsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesEventsListResponse) GetListInboxEventsResponse() *components.ListInboxEventsResponse {
	if i == nil {
		return nil
	}
	return i.ListInboxEventsResponse
}
