// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesListRequest struct {
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (i *InboxesListRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesListRequest) GetPageToken() *string {
	if i == nil {
		return nil
	}
	return i.PageToken
}

func (i *InboxesListRequest) GetAscending() *bool {
	if i == nil {
		return nil
	}
	return i.Ascending
}

type InboxesListResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	InboxesListInboxesResponse *components.InboxesListInboxesResponse
}

func (i InboxesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesListResponse) GetInboxesListInboxesResponse() *components.InboxesListInboxesResponse {
	if i == nil {
		return nil
	}
	return i.InboxesListInboxesResponse
}
