// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesDraftsUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesDraftsUpdateRequest struct {
	InboxID string                        `pathParam:"style=simple,explode=false,name=inbox_id"`
	DraftID string                        `pathParam:"style=simple,explode=false,name=draft_id"`
	Body    components.UpdateDraftRequest `request:"mediaType=application/json"`
}

func (i *InboxesDraftsUpdateRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesDraftsUpdateRequest) GetDraftID() string {
	if i == nil {
		return ""
	}
	return i.DraftID
}

func (i *InboxesDraftsUpdateRequest) GetBody() components.UpdateDraftRequest {
	if i == nil {
		return components.UpdateDraftRequest{}
	}
	return i.Body
}

type InboxesDraftsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Draft    *components.Draft
}

func (i InboxesDraftsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesDraftsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesDraftsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesDraftsUpdateResponse) GetDraft() *components.Draft {
	if i == nil {
		return nil
	}
	return i.Draft
}
