// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesThreadsGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesThreadsGetRequest struct {
	InboxID  string `pathParam:"style=simple,explode=false,name=inbox_id"`
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
}

func (i *InboxesThreadsGetRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesThreadsGetRequest) GetThreadID() string {
	if i == nil {
		return ""
	}
	return i.ThreadID
}

type InboxesThreadsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Thread   *components.Thread
}

func (i InboxesThreadsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesThreadsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesThreadsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesThreadsGetResponse) GetThread() *components.Thread {
	if i == nil {
		return nil
	}
	return i.Thread
}
