// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesUpdateRequest struct {
	InboxID string                               `pathParam:"style=simple,explode=false,name=inbox_id"`
	Body    components.InboxesUpdateInboxRequest `request:"mediaType=application/json"`
}

func (i *InboxesUpdateRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesUpdateRequest) GetBody() components.InboxesUpdateInboxRequest {
	if i == nil {
		return components.InboxesUpdateInboxRequest{}
	}
	return i.Body
}

type InboxesUpdateResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	InboxesInbox *components.InboxesInbox
}

func (i InboxesUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesUpdateResponse) GetInboxesInbox() *components.InboxesInbox {
	if i == nil {
		return nil
	}
	return i.InboxesInbox
}
