// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var InboxesAPIKeysDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesAPIKeysDeleteRequest struct {
	InboxID  string `pathParam:"style=simple,explode=false,name=inbox_id"`
	APIKeyID string `pathParam:"style=simple,explode=false,name=api_key_id"`
}

func (i *InboxesAPIKeysDeleteRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesAPIKeysDeleteRequest) GetAPIKeyID() string {
	if i == nil {
		return ""
	}
	return i.APIKeyID
}

type InboxesAPIKeysDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InboxesAPIKeysDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
