// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var InboxesDraftsDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesDraftsDeleteRequest struct {
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
	DraftID string `pathParam:"style=simple,explode=false,name=draft_id"`
}

func (i *InboxesDraftsDeleteRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesDraftsDeleteRequest) GetDraftID() string {
	if i == nil {
		return ""
	}
	return i.DraftID
}

type InboxesDraftsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InboxesDraftsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
