// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesMessagesGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesMessagesGetRequest struct {
	InboxID   string `pathParam:"style=simple,explode=false,name=inbox_id"`
	MessageID string `pathParam:"style=simple,explode=false,name=message_id"`
}

func (i *InboxesMessagesGetRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesMessagesGetRequest) GetMessageID() string {
	if i == nil {
		return ""
	}
	return i.MessageID
}

type InboxesMessagesGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Message  *components.Message
}

func (i InboxesMessagesGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesMessagesGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesMessagesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesMessagesGetResponse) GetMessage() *components.Message {
	if i == nil {
		return nil
	}
	return i.Message
}
