// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var InboxesAPIKeysListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type InboxesAPIKeysListRequest struct {
	InboxID   string  `pathParam:"style=simple,explode=false,name=inbox_id"`
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (i *InboxesAPIKeysListRequest) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesAPIKeysListRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesAPIKeysListRequest) GetPageToken() *string {
	if i == nil {
		return nil
	}
	return i.PageToken
}

type InboxesAPIKeysListResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	ListAPIKeysResponse *components.ListAPIKeysResponse
}

func (i InboxesAPIKeysListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesAPIKeysListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesAPIKeysListResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InboxesAPIKeysListResponse) GetListAPIKeysResponse() *components.ListAPIKeysResponse {
	if i == nil {
		return nil
	}
	return i.ListAPIKeysResponse
}
