// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var ListsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type ListsListRequest struct {
	// Direction of list entry.
	Direction components.Direction `pathParam:"style=simple,explode=false,name=direction"`
	// Type of list entry.
	Type      components.ListType `pathParam:"style=simple,explode=false,name=type"`
	Limit     *int64              `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string             `queryParam:"style=form,explode=true,name=page_token"`
}

func (l *ListsListRequest) GetDirection() components.Direction {
	if l == nil {
		return components.Direction("")
	}
	return l.Direction
}

func (l *ListsListRequest) GetType() components.ListType {
	if l == nil {
		return components.ListType("")
	}
	return l.Type
}

func (l *ListsListRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListsListRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

type ListsListResponse struct {
	HTTPMeta                components.HTTPMetadata `json:"-"`
	ListListEntriesResponse *components.ListListEntriesResponse
}

func (l ListsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListsListResponse) GetListListEntriesResponse() *components.ListListEntriesResponse {
	if l == nil {
		return nil
	}
	return l.ListListEntriesResponse
}
