// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var ListsCreateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type ListsCreateRequest struct {
	// Direction of list entry.
	Direction components.Direction `pathParam:"style=simple,explode=false,name=direction"`
	// Type of list entry.
	Type components.ListType               `pathParam:"style=simple,explode=false,name=type"`
	Body components.CreateListEntryRequest `request:"mediaType=application/json"`
}

func (l *ListsCreateRequest) GetDirection() components.Direction {
	if l == nil {
		return components.Direction("")
	}
	return l.Direction
}

func (l *ListsCreateRequest) GetType() components.ListType {
	if l == nil {
		return components.ListType("")
	}
	return l.Type
}

func (l *ListsCreateRequest) GetBody() components.CreateListEntryRequest {
	if l == nil {
		return components.CreateListEntryRequest{}
	}
	return l.Body
}

type ListsCreateResponse struct {
	HTTPMeta  components.HTTPMetadata `json:"-"`
	ListEntry *components.ListEntry
}

func (l ListsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListsCreateResponse) GetListEntry() *components.ListEntry {
	if l == nil {
		return nil
	}
	return l.ListEntry
}
