// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

var MetricsQueryServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type MetricsQueryRequest struct {
	EventTypes []components.MetricEventType `queryParam:"style=form,explode=true,name=event_types"`
	Start      *time.Time                   `queryParam:"style=form,explode=true,name=start"`
	End        *time.Time                   `queryParam:"style=form,explode=true,name=end"`
	Period     *string                      `queryParam:"style=form,explode=true,name=period"`
	Limit      *int64                       `queryParam:"style=form,explode=true,name=limit"`
	Descending *bool                        `queryParam:"style=form,explode=true,name=descending"`
}

func (m MetricsQueryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsQueryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsQueryRequest) GetEventTypes() []components.MetricEventType {
	if m == nil {
		return nil
	}
	return m.EventTypes
}

func (m *MetricsQueryRequest) GetStart() *time.Time {
	if m == nil {
		return nil
	}
	return m.Start
}

func (m *MetricsQueryRequest) GetEnd() *time.Time {
	if m == nil {
		return nil
	}
	return m.End
}

func (m *MetricsQueryRequest) GetPeriod() *string {
	if m == nil {
		return nil
	}
	return m.Period
}

func (m *MetricsQueryRequest) GetLimit() *int64 {
	if m == nil {
		return nil
	}
	return m.Limit
}

func (m *MetricsQueryRequest) GetDescending() *bool {
	if m == nil {
		return nil
	}
	return m.Descending
}

type MetricsQueryResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	QueryMetricsResponse map[string][]components.MetricBucket
}

func (m MetricsQueryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsQueryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsQueryResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MetricsQueryResponse) GetQueryMetricsResponse() map[string][]components.MetricBucket {
	if m == nil {
		return nil
	}
	return m.QueryMetricsResponse
}
