// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsInboxesGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsInboxesGetRequest struct {
	PodID   string `pathParam:"style=simple,explode=false,name=pod_id"`
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
}

func (p *PodsInboxesGetRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsInboxesGetRequest) GetInboxID() string {
	if p == nil {
		return ""
	}
	return p.InboxID
}

type PodsInboxesGetResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	InboxesInbox *components.InboxesInbox
}

func (p PodsInboxesGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsInboxesGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsInboxesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsInboxesGetResponse) GetInboxesInbox() *components.InboxesInbox {
	if p == nil {
		return nil
	}
	return p.InboxesInbox
}
