// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"io"
)

var PodsDomainsGetZoneFileServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsDomainsGetZoneFileRequest struct {
	PodID    string `pathParam:"style=simple,explode=false,name=pod_id"`
	DomainID string `pathParam:"style=simple,explode=false,name=domain_id"`
}

func (p *PodsDomainsGetZoneFileRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsDomainsGetZoneFileRequest) GetDomainID() string {
	if p == nil {
		return ""
	}
	return p.DomainID
}

type PodsDomainsGetZoneFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (p *PodsDomainsGetZoneFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsDomainsGetZoneFileResponse) GetResponseStream() io.ReadCloser {
	if p == nil {
		return nil
	}
	return p.ResponseStream
}
