// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsInboxesCreateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsInboxesCreateRequest struct {
	PodID string                               `pathParam:"style=simple,explode=false,name=pod_id"`
	Body  components.InboxesCreateInboxRequest `request:"mediaType=application/json"`
}

func (p *PodsInboxesCreateRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsInboxesCreateRequest) GetBody() components.InboxesCreateInboxRequest {
	if p == nil {
		return components.InboxesCreateInboxRequest{}
	}
	return p.Body
}

type PodsInboxesCreateResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	InboxesInbox *components.InboxesInbox
}

func (p PodsInboxesCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsInboxesCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsInboxesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsInboxesCreateResponse) GetInboxesInbox() *components.InboxesInbox {
	if p == nil {
		return nil
	}
	return p.InboxesInbox
}
