// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsInboxesUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsInboxesUpdateRequest struct {
	PodID   string                               `pathParam:"style=simple,explode=false,name=pod_id"`
	InboxID string                               `pathParam:"style=simple,explode=false,name=inbox_id"`
	Body    components.InboxesUpdateInboxRequest `request:"mediaType=application/json"`
}

func (p *PodsInboxesUpdateRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsInboxesUpdateRequest) GetInboxID() string {
	if p == nil {
		return ""
	}
	return p.InboxID
}

func (p *PodsInboxesUpdateRequest) GetBody() components.InboxesUpdateInboxRequest {
	if p == nil {
		return components.InboxesUpdateInboxRequest{}
	}
	return p.Body
}

type PodsInboxesUpdateResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	InboxesInbox *components.InboxesInbox
}

func (p PodsInboxesUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsInboxesUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsInboxesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsInboxesUpdateResponse) GetInboxesInbox() *components.InboxesInbox {
	if p == nil {
		return nil
	}
	return p.InboxesInbox
}
