// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

var PodsDraftsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsDraftsListRequest struct {
	PodID     string     `pathParam:"style=simple,explode=false,name=pod_id"`
	Limit     *int64     `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string    `queryParam:"style=form,explode=true,name=page_token"`
	Labels    []string   `queryParam:"style=form,explode=true,name=labels"`
	Before    *time.Time `queryParam:"style=form,explode=true,name=before"`
	After     *time.Time `queryParam:"style=form,explode=true,name=after"`
	Ascending *bool      `queryParam:"style=form,explode=true,name=ascending"`
}

func (p PodsDraftsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsDraftsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsDraftsListRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsDraftsListRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PodsDraftsListRequest) GetPageToken() *string {
	if p == nil {
		return nil
	}
	return p.PageToken
}

func (p *PodsDraftsListRequest) GetLabels() []string {
	if p == nil {
		return nil
	}
	return p.Labels
}

func (p *PodsDraftsListRequest) GetBefore() *time.Time {
	if p == nil {
		return nil
	}
	return p.Before
}

func (p *PodsDraftsListRequest) GetAfter() *time.Time {
	if p == nil {
		return nil
	}
	return p.After
}

func (p *PodsDraftsListRequest) GetAscending() *bool {
	if p == nil {
		return nil
	}
	return p.Ascending
}

type PodsDraftsListResponse struct {
	HTTPMeta           components.HTTPMetadata `json:"-"`
	ListDraftsResponse *components.ListDraftsResponse
}

func (p PodsDraftsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsDraftsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsDraftsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsDraftsListResponse) GetListDraftsResponse() *components.ListDraftsResponse {
	if p == nil {
		return nil
	}
	return p.ListDraftsResponse
}
