// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsAPIKeysCreateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsAPIKeysCreateRequest struct {
	PodID string                         `pathParam:"style=simple,explode=false,name=pod_id"`
	Body  components.CreateAPIKeyRequest `request:"mediaType=application/json"`
}

func (p *PodsAPIKeysCreateRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsAPIKeysCreateRequest) GetBody() components.CreateAPIKeyRequest {
	if p == nil {
		return components.CreateAPIKeyRequest{}
	}
	return p.Body
}

type PodsAPIKeysCreateResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	CreateAPIKeyResponse *components.CreateAPIKeyResponse
}

func (p PodsAPIKeysCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsAPIKeysCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsAPIKeysCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsAPIKeysCreateResponse) GetCreateAPIKeyResponse() *components.CreateAPIKeyResponse {
	if p == nil {
		return nil
	}
	return p.CreateAPIKeyResponse
}
