// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsDomainsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsDomainsListRequest struct {
	PodID     string  `pathParam:"style=simple,explode=false,name=pod_id"`
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (p *PodsDomainsListRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsDomainsListRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PodsDomainsListRequest) GetPageToken() *string {
	if p == nil {
		return nil
	}
	return p.PageToken
}

func (p *PodsDomainsListRequest) GetAscending() *bool {
	if p == nil {
		return nil
	}
	return p.Ascending
}

type PodsDomainsListResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	ListDomainsResponse *components.ListDomainsResponse
}

func (p PodsDomainsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsDomainsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsDomainsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsDomainsListResponse) GetListDomainsResponse() *components.ListDomainsResponse {
	if p == nil {
		return nil
	}
	return p.ListDomainsResponse
}
