// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var PodsInboxesDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsInboxesDeleteRequest struct {
	PodID   string `pathParam:"style=simple,explode=false,name=pod_id"`
	InboxID string `pathParam:"style=simple,explode=false,name=inbox_id"`
}

func (p *PodsInboxesDeleteRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsInboxesDeleteRequest) GetInboxID() string {
	if p == nil {
		return ""
	}
	return p.InboxID
}

type PodsInboxesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (p *PodsInboxesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}
