// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsDomainsGetServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsDomainsGetRequest struct {
	PodID    string `pathParam:"style=simple,explode=false,name=pod_id"`
	DomainID string `pathParam:"style=simple,explode=false,name=domain_id"`
}

func (p *PodsDomainsGetRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsDomainsGetRequest) GetDomainID() string {
	if p == nil {
		return ""
	}
	return p.DomainID
}

type PodsDomainsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Domain   *components.Domain
}

func (p PodsDomainsGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsDomainsGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsDomainsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsDomainsGetResponse) GetDomain() *components.Domain {
	if p == nil {
		return nil
	}
	return p.Domain
}
