// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsInboxesListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsInboxesListRequest struct {
	PodID     string  `pathParam:"style=simple,explode=false,name=pod_id"`
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (p *PodsInboxesListRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsInboxesListRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PodsInboxesListRequest) GetPageToken() *string {
	if p == nil {
		return nil
	}
	return p.PageToken
}

func (p *PodsInboxesListRequest) GetAscending() *bool {
	if p == nil {
		return nil
	}
	return p.Ascending
}

type PodsInboxesListResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	InboxesListInboxesResponse *components.InboxesListInboxesResponse
}

func (p PodsInboxesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsInboxesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsInboxesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsInboxesListResponse) GetInboxesListInboxesResponse() *components.InboxesListInboxesResponse {
	if p == nil {
		return nil
	}
	return p.InboxesListInboxesResponse
}
