// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

var PodsMetricsQueryServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsMetricsQueryRequest struct {
	PodID      string                       `pathParam:"style=simple,explode=false,name=pod_id"`
	EventTypes []components.MetricEventType `queryParam:"style=form,explode=true,name=event_types"`
	Start      *time.Time                   `queryParam:"style=form,explode=true,name=start"`
	End        *time.Time                   `queryParam:"style=form,explode=true,name=end"`
	Period     *string                      `queryParam:"style=form,explode=true,name=period"`
	Limit      *int64                       `queryParam:"style=form,explode=true,name=limit"`
	Descending *bool                        `queryParam:"style=form,explode=true,name=descending"`
}

func (p PodsMetricsQueryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsMetricsQueryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsMetricsQueryRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsMetricsQueryRequest) GetEventTypes() []components.MetricEventType {
	if p == nil {
		return nil
	}
	return p.EventTypes
}

func (p *PodsMetricsQueryRequest) GetStart() *time.Time {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *PodsMetricsQueryRequest) GetEnd() *time.Time {
	if p == nil {
		return nil
	}
	return p.End
}

func (p *PodsMetricsQueryRequest) GetPeriod() *string {
	if p == nil {
		return nil
	}
	return p.Period
}

func (p *PodsMetricsQueryRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PodsMetricsQueryRequest) GetDescending() *bool {
	if p == nil {
		return nil
	}
	return p.Descending
}

type PodsMetricsQueryResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	QueryMetricsResponse map[string][]components.MetricBucket
}

func (p PodsMetricsQueryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsMetricsQueryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsMetricsQueryResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsMetricsQueryResponse) GetQueryMetricsResponse() map[string][]components.MetricBucket {
	if p == nil {
		return nil
	}
	return p.QueryMetricsResponse
}
