// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsListRequest struct {
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (p *PodsListRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PodsListRequest) GetPageToken() *string {
	if p == nil {
		return nil
	}
	return p.PageToken
}

func (p *PodsListRequest) GetAscending() *bool {
	if p == nil {
		return nil
	}
	return p.Ascending
}

type PodsListResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	PodsListPodsResponse *components.PodsListPodsResponse
}

func (p PodsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsListResponse) GetPodsListPodsResponse() *components.PodsListPodsResponse {
	if p == nil {
		return nil
	}
	return p.PodsListPodsResponse
}
