// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var PodsAPIKeysDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsAPIKeysDeleteRequest struct {
	PodID    string `pathParam:"style=simple,explode=false,name=pod_id"`
	APIKeyID string `pathParam:"style=simple,explode=false,name=api_key_id"`
}

func (p *PodsAPIKeysDeleteRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsAPIKeysDeleteRequest) GetAPIKeyID() string {
	if p == nil {
		return ""
	}
	return p.APIKeyID
}

type PodsAPIKeysDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (p *PodsAPIKeysDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}
