// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var PodsDomainsCreateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type PodsDomainsCreateRequest struct {
	PodID string                         `pathParam:"style=simple,explode=false,name=pod_id"`
	Body  components.CreateDomainRequest `request:"mediaType=application/json"`
}

func (p *PodsDomainsCreateRequest) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodsDomainsCreateRequest) GetBody() components.CreateDomainRequest {
	if p == nil {
		return components.CreateDomainRequest{}
	}
	return p.Body
}

type PodsDomainsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Domain   *components.Domain
}

func (p PodsDomainsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodsDomainsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodsDomainsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PodsDomainsCreateResponse) GetDomain() *components.Domain {
	if p == nil {
		return nil
	}
	return p.Domain
}
