// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var ThreadsGetAttachmentServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type ThreadsGetAttachmentRequest struct {
	ThreadID     string `pathParam:"style=simple,explode=false,name=thread_id"`
	AttachmentID string `pathParam:"style=simple,explode=false,name=attachment_id"`
}

func (t *ThreadsGetAttachmentRequest) GetThreadID() string {
	if t == nil {
		return ""
	}
	return t.ThreadID
}

func (t *ThreadsGetAttachmentRequest) GetAttachmentID() string {
	if t == nil {
		return ""
	}
	return t.AttachmentID
}

type ThreadsGetAttachmentResponse struct {
	HTTPMeta           components.HTTPMetadata `json:"-"`
	AttachmentResponse *components.AttachmentResponse
}

func (t ThreadsGetAttachmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ThreadsGetAttachmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ThreadsGetAttachmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *ThreadsGetAttachmentResponse) GetAttachmentResponse() *components.AttachmentResponse {
	if t == nil {
		return nil
	}
	return t.AttachmentResponse
}
