// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/optionalnullable"
)

var ThreadsDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type ThreadsDeleteRequest struct {
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
	// If true, permanently delete the thread instead of moving to trash.
	Permanent optionalnullable.OptionalNullable[bool] `queryParam:"style=form,explode=true,name=permanent"`
}

func (t *ThreadsDeleteRequest) GetThreadID() string {
	if t == nil {
		return ""
	}
	return t.ThreadID
}

func (t *ThreadsDeleteRequest) GetPermanent() optionalnullable.OptionalNullable[bool] {
	if t == nil {
		return nil
	}
	return t.Permanent
}

type ThreadsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (t *ThreadsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}
