// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var ThreadsUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type ThreadsUpdateRequest struct {
	ThreadID string                         `pathParam:"style=simple,explode=false,name=thread_id"`
	Body     components.UpdateThreadRequest `request:"mediaType=application/json"`
}

func (t *ThreadsUpdateRequest) GetThreadID() string {
	if t == nil {
		return ""
	}
	return t.ThreadID
}

func (t *ThreadsUpdateRequest) GetBody() components.UpdateThreadRequest {
	if t == nil {
		return components.UpdateThreadRequest{}
	}
	return t.Body
}

type ThreadsUpdateResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	UpdateThreadResponse *components.UpdateThreadResponse
}

func (t ThreadsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ThreadsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ThreadsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *ThreadsUpdateResponse) GetUpdateThreadResponse() *components.UpdateThreadResponse {
	if t == nil {
		return nil
	}
	return t.UpdateThreadResponse
}
