// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var WebhooksUpdateServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type WebhooksUpdateRequest struct {
	WebhookID string                                  `pathParam:"style=simple,explode=false,name=webhook_id"`
	Body      components.WebhooksUpdateWebhookRequest `request:"mediaType=application/json"`
}

func (w *WebhooksUpdateRequest) GetWebhookID() string {
	if w == nil {
		return ""
	}
	return w.WebhookID
}

func (w *WebhooksUpdateRequest) GetBody() components.WebhooksUpdateWebhookRequest {
	if w == nil {
		return components.WebhooksUpdateWebhookRequest{}
	}
	return w.Body
}

type WebhooksUpdateResponse struct {
	HTTPMeta        components.HTTPMetadata `json:"-"`
	WebhooksWebhook *components.WebhooksWebhook
}

func (w WebhooksUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhooksUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhooksUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WebhooksUpdateResponse) GetWebhooksWebhook() *components.WebhooksWebhook {
	if w == nil {
		return nil
	}
	return w.WebhooksWebhook
}
