// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

var WebhooksListServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type WebhooksListRequest struct {
	Limit     *int64  `queryParam:"style=form,explode=true,name=limit"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	Ascending *bool   `queryParam:"style=form,explode=true,name=ascending"`
}

func (w *WebhooksListRequest) GetLimit() *int64 {
	if w == nil {
		return nil
	}
	return w.Limit
}

func (w *WebhooksListRequest) GetPageToken() *string {
	if w == nil {
		return nil
	}
	return w.PageToken
}

func (w *WebhooksListRequest) GetAscending() *bool {
	if w == nil {
		return nil
	}
	return w.Ascending
}

type WebhooksListResponse struct {
	HTTPMeta                     components.HTTPMetadata `json:"-"`
	WebhooksListWebhooksResponse *components.WebhooksListWebhooksResponse
}

func (w WebhooksListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhooksListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhooksListResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WebhooksListResponse) GetWebhooksListWebhooksResponse() *components.WebhooksListWebhooksResponse {
	if w == nil {
		return nil
	}
	return w.WebhooksListWebhooksResponse
}
