// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"agentmail-cli/internal/sdk/models/components"
)

var WebhooksDeleteServerList = []string{
	"https://api.agentmail.to",
	"https://x402.api.agentmail.to",
	"https://mpp.api.agentmail.to",
	"https://api.agentmail.eu",
}

type WebhooksDeleteRequest struct {
	WebhookID string `pathParam:"style=simple,explode=false,name=webhook_id"`
}

func (w *WebhooksDeleteRequest) GetWebhookID() string {
	if w == nil {
		return ""
	}
	return w.WebhookID
}

type WebhooksDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (w *WebhooksDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}
