// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxes

import (
	"agentmail-cli/internal/cli/inboxes/events"
	"agentmail-cli/internal/cli/inboxes/inboxesapikeys"
	"agentmail-cli/internal/cli/inboxes/inboxesdrafts"
	"agentmail-cli/internal/cli/inboxes/inboxeslists"
	"agentmail-cli/internal/cli/inboxes/inboxesmetrics"
	"agentmail-cli/internal/cli/inboxes/inboxesthreads"
	"agentmail-cli/internal/cli/inboxes/messages"
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInboxesRoot(parent *cobra.Command) error {
	var InboxesCmd = &cobra.Command{
		Use:   "inboxes",
		Short: "Operations for inboxes",
		Long:  "Operations for inboxes",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := inboxesapikeys.InitInboxesApiKeysRoot(InboxesCmd); err != nil {
		return err
	}
	if err := inboxesdrafts.InitInboxesDraftsRoot(InboxesCmd); err != nil {
		return err
	}
	if err := events.InitEventsRoot(InboxesCmd); err != nil {
		return err
	}
	if err := inboxeslists.InitInboxesListsRoot(InboxesCmd); err != nil {
		return err
	}
	if err := messages.InitMessagesRoot(InboxesCmd); err != nil {
		return err
	}
	if err := inboxesmetrics.InitInboxesMetricsRoot(InboxesCmd); err != nil {
		return err
	}
	if err := inboxesthreads.InitInboxesThreadsRoot(InboxesCmd); err != nil {
		return err
	}

	if err := initInboxesListCmd(InboxesCmd); err != nil {
		return err
	}

	if err := initInboxesCreateCmd(InboxesCmd); err != nil {
		return err
	}

	if err := initInboxesGetCmd(InboxesCmd); err != nil {
		return err
	}

	if err := initInboxesUpdateCmd(InboxesCmd); err != nil {
		return err
	}

	if err := initInboxesDeleteCmd(InboxesCmd); err != nil {
		return err
	}

	parent.AddCommand(InboxesCmd)
	return nil
}
