// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package podslists

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var podsListsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pod-id", Shorthand: "p", FieldPath: "PodID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "direction", FieldPath: "Direction", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"send", "receive", "reply"}, Description: "Direction of list entry. (options: send, receive, reply) [required]"},
	{FlagName: "type", Shorthand: "t", FieldPath: "Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"allow", "block"}, Description: "Type of list entry. (options: allow, block) [required]"},
	{FlagName: "entry", Shorthand: "e", FieldPath: "Entry", Kind: flagutil.FlagKindString, Required: true, Description: "Email address or domain. [required]"},
}

// initPodsListsDeleteCmd initializes the pods-lists-delete command.
func initPodsListsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete List Entry",
		Long:    "**CLI:**\n```bash\nagentmail pods:lists delete --pod-id <pod_id> --direction <direction> --type <type> --entry <entry>\n```",
		Example: "  agentmail pods-lists delete --pod-id <id> --direction reply --type block --entry <value>",
		RunE:    runPodsListsDeleteCmd,
	}
	flagutil.RegisterFlags(cmd, podsListsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.PodsListsDeleteRequest](podsListsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pods-lists-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPodsListsDeleteCmd executes the pods-lists-delete command.
func runPodsListsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, podsListsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, podsListsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PodsListsDeleteRequest](cmd, podsListsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.PodsListsDeleteServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.PodsListsDeleteServerList)-1)
		}
		serverURL := operations.PodsListsDeleteServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PodsLists.PodsListsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
