// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package podslists

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var podsListsCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pod-id", Shorthand: "p", FieldPath: "PodID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "direction", FieldPath: "Direction", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"send", "receive", "reply"}, Description: "Direction of list entry. (options: send, receive, reply) [required]"},
	{FlagName: "type", Shorthand: "t", FieldPath: "Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"allow", "block"}, Description: "Type of list entry. (options: allow, block) [required]"},
	{FlagName: "entry", Shorthand: "e", FieldPath: "Body.Entry", Kind: flagutil.FlagKindString, Required: true, Description: "Email address or domain to add. [required]"},
	{FlagName: "reason", Shorthand: "r", FieldPath: "Body.Reason", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"reason,omitempty"`, Description: "Reason for adding the entry."},
}

// initPodsListsCreateCmd initializes the pods-lists-create command.
func initPodsListsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create List Entry",
		Long:    "**CLI:**\n```bash\nagentmail pods:lists create --pod-id <pod_id> --direction <direction> --type <type> --entry user@example.com\n```",
		Example: "  agentmail pods-lists create --pod-id <id> --direction send --type allow --entry <value>",
		RunE:    runPodsListsCreateCmd,
	}
	flagutil.RegisterFlags(cmd, podsListsCreateCmdMeta)
	if err := flagutil.ValidateMeta[operations.PodsListsCreateRequest](podsListsCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pods-lists-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPodsListsCreateCmd executes the pods-lists-create command.
func runPodsListsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, podsListsCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, podsListsCreateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PodsListsCreateRequest](cmd, podsListsCreateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.PodsListsCreateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.PodsListsCreateServerList)-1)
		}
		serverURL := operations.PodsListsCreateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PodsLists.PodsListsCreate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
