// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

// Generated from  generator version 2.881.2

import (
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/retry"
	"agentmail-cli/internal/sdk/sdkinternal/config"
	"agentmail-cli/internal/sdk/sdkinternal/hooks"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"context"
	"net/http"
	"time"
)

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

type AgentmailCli struct {
	SDKVersion      string
	Inboxes         *Inboxes
	Pods            *Pods
	Webhooks        *Webhooks
	Agent           *Agent
	APIKeys         *APIKeys
	Domains         *Domains
	Drafts          *Drafts
	InboxesAPIKeys  *InboxesAPIKeys
	InboxesDrafts   *InboxesDrafts
	InboxesEvents   *InboxesEvents
	InboxesLists    *InboxesLists
	InboxesMessages *InboxesMessages
	InboxesMetrics  *InboxesMetrics
	InboxesThreads  *InboxesThreads
	Lists           *Lists
	Metrics         *Metrics
	Organizations   *Organizations
	PodsAPIKeys     *PodsAPIKeys
	PodsDomains     *PodsDomains
	PodsDrafts      *PodsDrafts
	PodsInboxes     *PodsInboxes
	PodsLists       *PodsLists
	PodsMetrics     *PodsMetrics
	PodsThreads     *PodsThreads
	Threads         *Threads

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*AgentmailCli)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *AgentmailCli) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *AgentmailCli) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *AgentmailCli) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security components.Security) SDKOption {
	return func(sdk *AgentmailCli) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *AgentmailCli) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *AgentmailCli) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *AgentmailCli) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *AgentmailCli {
	sdk := &AgentmailCli{
		SDKVersion: "0.0.1",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent: "speakeasy-sdk/go 0.0.1 2.881.2 agentmail-cli/internal/sdk",
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Inboxes = newInboxes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Pods = newPods(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Webhooks = newWebhooks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Agent = newAgent(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.APIKeys = newAPIKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Domains = newDomains(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Drafts = newDrafts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesAPIKeys = newInboxesAPIKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesDrafts = newInboxesDrafts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesEvents = newInboxesEvents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesLists = newInboxesLists(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesMessages = newInboxesMessages(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesMetrics = newInboxesMetrics(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InboxesThreads = newInboxesThreads(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Lists = newLists(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Metrics = newMetrics(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Organizations = newOrganizations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsAPIKeys = newPodsAPIKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsDomains = newPodsDomains(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsDrafts = newPodsDrafts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsInboxes = newPodsInboxes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsLists = newPodsLists(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsMetrics = newPodsMetrics(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PodsThreads = newPodsThreads(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Threads = newThreads(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
