// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var apiKeysListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "page-token", Shorthand: "p", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "ascending", Shorthand: "a", FieldPath: "Ascending", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initApiKeysListCmd initializes the api-keys-list command.
func initApiKeysListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List API Keys",
		Long:    "**CLI:**\n```bash\nagentmail api-keys list\n```",
		Example: "  agentmail api-keys list",
		RunE:    runApiKeysListCmd,
	}
	flagutil.RegisterFlags(cmd, apiKeysListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIKeysListRequest](apiKeysListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-keys-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiKeysListCmd executes the api-keys-list command.
func runApiKeysListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiKeysListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiKeysListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIKeysListRequest](cmd, apiKeysListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.APIKeysListServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.APIKeysListServerList)-1)
		}
		serverURL := operations.APIKeysListServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIKeys.APIKeysList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
