// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var apiKeysDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "api-key-id", Shorthand: "a", FieldPath: "APIKeyID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApiKeysDeleteCmd initializes the api-keys-delete command.
func initApiKeysDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "api-keys-delete",
		Short:   "Delete API Key",
		Long:    "**CLI:**\n```bash\nagentmail api-keys delete --api-key-id <api_key_id>\n```",
		Example: "  cli API-keys api-keys-delete --api-key-id <id>",
		RunE:    runApiKeysDeleteCmd,
		Aliases: []string{"akd"},
	}
	flagutil.RegisterFlags(cmd, apiKeysDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIKeysDeleteRequest](apiKeysDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-keys-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiKeysDeleteCmd executes the api-keys-delete command.
func runApiKeysDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiKeysDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiKeysDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIKeysDeleteRequest](cmd, apiKeysDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.APIKeysDeleteServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.APIKeysDeleteServerList)-1)
		}
		serverURL := operations.APIKeysDeleteServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIKeys.APIKeysDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
