// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitApiKeysRoot(parent *cobra.Command) error {
	var ApiKeysCmd = &cobra.Command{
		Use:   "api-keys",
		Short: "Operations for api-keys",
		Long:  "Operations for api-keys",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ak"},
	}

	if err := initApiKeysListCmd(ApiKeysCmd); err != nil {
		return err
	}

	if err := initApiKeysCreateCmd(ApiKeysCmd); err != nil {
		return err
	}

	if err := initApiKeysDeleteCmd(ApiKeysCmd); err != nil {
		return err
	}

	parent.AddCommand(ApiKeysCmd)
	return nil
}
