// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitAPIKeysRoot(parent *cobra.Command) error {
	var APIKeysCmd = &cobra.Command{
		Use:   "API-keys",
		Short: "Operations for API-keys",
		Long:  "Operations for API-keys",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"Ak"},
	}

	if err := initApiKeysListCmd(APIKeysCmd); err != nil {
		return err
	}

	if err := initApiKeysCreateCmd(APIKeysCmd); err != nil {
		return err
	}

	if err := initApiKeysDeleteCmd(APIKeysCmd); err != nil {
		return err
	}

	parent.AddCommand(APIKeysCmd)
	return nil
}
