// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"agentmail-cli/internal/sdk/models/components"
	"encoding/json"
)

type ErrorResponse struct {
	// Name of error.
	Name string `json:"name"`
	// Error message.
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
