// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package events

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesEventsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "page-token", Shorthand: "p", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "ascending", Shorthand: "a", FieldPath: "Ascending", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initInboxesEventsListCmd initializes the inboxes-events-list command.
func initInboxesEventsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "inboxes-events-list",
		Short:   "List Inbox Events",
		Long:    "List label change events for an inbox. Returns events in reverse chronological order by default. Use for IMAP UID projection or audit logging.\n\n**CLI:**\n```bash\nagentmail inboxes:events list --inbox-id <inbox_id>\n```",
		Example: "  agentmail events inboxes-events-list --inbox-id <id>",
		RunE:    runInboxesEventsListCmd,
		Aliases: []string{"iel"},
	}
	flagutil.RegisterFlags(cmd, inboxesEventsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesEventsListRequest](inboxesEventsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-events-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesEventsListCmd executes the inboxes-events-list command.
func runInboxesEventsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesEventsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesEventsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesEventsListRequest](cmd, inboxesEventsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesEventsListServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesEventsListServerList)-1)
		}
		serverURL := operations.InboxesEventsListServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Events.InboxesEventsList(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
