// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package podsthreads

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var podsThreadsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pod-id", FieldPath: "PodID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "limit", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "page-token", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "labels", FieldPath: "Labels", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
	{FlagName: "before", Shorthand: "b", FieldPath: "Before", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "after", FieldPath: "After", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "ascending", FieldPath: "Ascending", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "include-spam", FieldPath: "IncludeSpam", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "include-blocked", FieldPath: "IncludeBlocked", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "include-trash", FieldPath: "IncludeTrash", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initPodsThreadsListCmd initializes the pods-threads-list command.
func initPodsThreadsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Threads",
		Long:    "**CLI:**\n```bash\nagentmail pods:threads list --pod-id <pod_id>\n```",
		Example: "  cli pods-threads list --pod-id <id>",
		RunE:    runPodsThreadsListCmd,
	}
	flagutil.RegisterFlags(cmd, podsThreadsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.PodsThreadsListRequest](podsThreadsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pods-threads-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPodsThreadsListCmd executes the pods-threads-list command.
func runPodsThreadsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, podsThreadsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, podsThreadsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PodsThreadsListRequest](cmd, podsThreadsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.PodsThreadsListServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.PodsThreadsListServerList)-1)
		}
		serverURL := operations.PodsThreadsListServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PodsThreads.PodsThreadsList(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
