// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesthreads

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesThreadsGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "thread-id", Shorthand: "t", FieldPath: "ThreadID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initInboxesThreadsGetCmd initializes the inboxes-threads-get command.
func initInboxesThreadsGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Thread",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:threads get --inbox-id <inbox_id> --thread-id <thread_id>\n```",
		Example: "  agentmail inboxes-threads get --inbox-id <id> --thread-id <id>",
		RunE:    runInboxesThreadsGetCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesThreadsGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesThreadsGetRequest](inboxesThreadsGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-threads-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesThreadsGetCmd executes the inboxes-threads-get command.
func runInboxesThreadsGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesThreadsGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesThreadsGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesThreadsGetRequest](cmd, inboxesThreadsGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesThreadsGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesThreadsGetServerList)-1)
		}
		serverURL := operations.InboxesThreadsGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Threads.InboxesThreadsGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
