// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesthreads

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesThreadsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "thread-id", Shorthand: "t", FieldPath: "ThreadID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "add-labels", Shorthand: "a", FieldPath: "Body.AddLabels", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"add_labels,omitempty"`, Description: "Labels to add to thread. Cannot be system labels."},
	{FlagName: "remove-labels", Shorthand: "r", FieldPath: "Body.RemoveLabels", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"remove_labels,omitempty"`, Description: "Labels to remove from thread. Cannot be system labels. Takes priority over `add_labels` (in the event of duplicate labels passed in)."},
}

// initInboxesThreadsUpdateCmd initializes the inboxes-threads-update command.
func initInboxesThreadsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update Thread",
		Long:    "Updates thread labels. Cannot add or remove system labels (sent, received, bounced, etc.). Rejects requests with a `422` for threads with 100 or more messages.",
		Example: "  agentmail inboxes-threads update --inbox-id <id> --thread-id <id>",
		RunE:    runInboxesThreadsUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesThreadsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesThreadsUpdateRequest](inboxesThreadsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-threads-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runInboxesThreadsUpdateCmd executes the inboxes-threads-update command.
func runInboxesThreadsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesThreadsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesThreadsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesThreadsUpdateRequest](cmd, inboxesThreadsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesThreadsUpdateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesThreadsUpdateServerList)-1)
		}
		serverURL := operations.InboxesThreadsUpdateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Threads.InboxesThreadsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
