// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesthreads

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInboxesThreadsRoot(parent *cobra.Command) error {
	var InboxesThreadsCmd = &cobra.Command{
		Use:   "threads",
		Short: "Operations for inboxes-threads",
		Long:  "Operations for inboxes-threads",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initInboxesThreadsListCmd(InboxesThreadsCmd); err != nil {
		return err
	}

	if err := initInboxesThreadsGetCmd(InboxesThreadsCmd); err != nil {
		return err
	}

	if err := initInboxesThreadsUpdateCmd(InboxesThreadsCmd); err != nil {
		return err
	}

	if err := initInboxesThreadsDeleteCmd(InboxesThreadsCmd); err != nil {
		return err
	}

	if err := initInboxesThreadsGetAttachmentCmd(InboxesThreadsCmd); err != nil {
		return err
	}

	parent.AddCommand(InboxesThreadsCmd)
	return nil
}
