// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package drafts

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var draftsGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "draft-id", FieldPath: "DraftID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDraftsGetCmd initializes the drafts-get command.
func initDraftsGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Draft",
		Long:    "**CLI:**\n```bash\nagentmail drafts get --draft-id <draft_id>\n```",
		Example: "  agentmail drafts get --draft-id <id>",
		RunE:    runDraftsGetCmd,
	}
	flagutil.RegisterFlags(cmd, draftsGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.DraftsGetRequest](draftsGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for drafts-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDraftsGetCmd executes the drafts-get command.
func runDraftsGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, draftsGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, draftsGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DraftsGetRequest](cmd, draftsGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.DraftsGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.DraftsGetServerList)-1)
		}
		serverURL := operations.DraftsGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Drafts.DraftsGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
