// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package drafts

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var draftsGetAttachmentCmdMeta = []flagutil.FlagMeta{
	{FlagName: "draft-id", FieldPath: "DraftID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "attachment-id", Shorthand: "a", FieldPath: "AttachmentID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDraftsGetAttachmentCmd initializes the drafts-get-attachment command.
func initDraftsGetAttachmentCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-attachment",
		Short:   "Get Attachment",
		Long:    "**CLI:**\n```bash\nagentmail drafts get-attachment --draft-id <draft_id> --attachment-id <attachment_id>\n```",
		Example: "  cli drafts get-attachment --draft-id <id> --attachment-id <id>",
		RunE:    runDraftsGetAttachmentCmd,
		Aliases: []string{"ga"},
	}
	flagutil.RegisterFlags(cmd, draftsGetAttachmentCmdMeta)
	if err := flagutil.ValidateMeta[operations.DraftsGetAttachmentRequest](draftsGetAttachmentCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for drafts-get-attachment: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDraftsGetAttachmentCmd executes the drafts-get-attachment command.
func runDraftsGetAttachmentCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, draftsGetAttachmentCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, draftsGetAttachmentCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DraftsGetAttachmentRequest](cmd, draftsGetAttachmentCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.DraftsGetAttachmentServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.DraftsGetAttachmentServerList)-1)
		}
		serverURL := operations.DraftsGetAttachmentServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Drafts.DraftsGetAttachment(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
