// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package drafts

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitDraftsRoot(parent *cobra.Command) error {
	var DraftsCmd = &cobra.Command{
		Use:   "drafts",
		Short: "Operations for drafts",
		Long:  "Operations for drafts",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initDraftsListCmd(DraftsCmd); err != nil {
		return err
	}

	if err := initDraftsGetCmd(DraftsCmd); err != nil {
		return err
	}

	if err := initDraftsGetAttachmentCmd(DraftsCmd); err != nil {
		return err
	}

	parent.AddCommand(DraftsCmd)
	return nil
}
