// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesdrafts

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesDraftsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "draft-id", FieldPath: "DraftID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "reply-to", Shorthand: "r", FieldPath: "Body.ReplyTo", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Reply-to addresses. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "to", FieldPath: "Body.To", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "cc", Shorthand: "c", FieldPath: "Body.Cc", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "bcc", Shorthand: "b", FieldPath: "Body.Bcc", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "subject", FieldPath: "Body.Subject", Kind: flagutil.FlagKindString, Optional: true, Description: "Subject of draft."},
	{FlagName: "text", FieldPath: "Body.Text", Kind: flagutil.FlagKindString, Optional: true, Description: "Plain text body of draft."},
	{FlagName: "html", FieldPath: "Body.HTML", Kind: flagutil.FlagKindString, Optional: true, Description: "HTML body of draft."},
	{FlagName: "send-at", FieldPath: "Body.SendAt", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "Time at which to schedule send draft."},
}

// initInboxesDraftsUpdateCmd initializes the inboxes-drafts-update command.
func initInboxesDraftsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update Draft",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:drafts update --inbox-id <inbox_id> --draft-id <draft_id> --subject \"Updated subject\"\n```",
		Example: "  cli inboxes-drafts update --inbox-id <id> --draft-id <id>",
		RunE:    runInboxesDraftsUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesDraftsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesDraftsUpdateRequest](inboxesDraftsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-drafts-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runInboxesDraftsUpdateCmd executes the inboxes-drafts-update command.
func runInboxesDraftsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesDraftsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesDraftsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesDraftsUpdateRequest](cmd, inboxesDraftsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesDraftsUpdateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesDraftsUpdateServerList)-1)
		}
		serverURL := operations.InboxesDraftsUpdateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InboxesDrafts.InboxesDraftsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
