// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesdrafts

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesDraftsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "draft-id", FieldPath: "DraftID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initInboxesDraftsDeleteCmd initializes the inboxes-drafts-delete command.
func initInboxesDraftsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Draft",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:drafts delete --inbox-id <inbox_id> --draft-id <draft_id>\n```",
		Example: "  cli inboxes-drafts delete --inbox-id <id> --draft-id <id>",
		RunE:    runInboxesDraftsDeleteCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesDraftsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesDraftsDeleteRequest](inboxesDraftsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-drafts-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesDraftsDeleteCmd executes the inboxes-drafts-delete command.
func runInboxesDraftsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesDraftsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesDraftsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesDraftsDeleteRequest](cmd, inboxesDraftsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesDraftsDeleteServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesDraftsDeleteServerList)-1)
		}
		serverURL := operations.InboxesDraftsDeleteServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InboxesDrafts.InboxesDraftsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
