// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitOrganizationsRoot(parent *cobra.Command) error {
	var OrganizationsCmd = &cobra.Command{
		Use:   "organizations",
		Short: "Operations for organizations",
		Long:  "Operations for organizations",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initOrganizationsGetCmd(OrganizationsCmd); err != nil {
		return err
	}

	parent.AddCommand(OrganizationsCmd)
	return nil
}
