// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package lists

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitListsRoot(parent *cobra.Command) error {
	var ListsCmd = &cobra.Command{
		Use:   "lists",
		Short: "Operations for lists",
		Long:  "Operations for lists",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListsListCmd(ListsCmd); err != nil {
		return err
	}

	if err := initListsCreateCmd(ListsCmd); err != nil {
		return err
	}

	if err := initListsGetCmd(ListsCmd); err != nil {
		return err
	}

	if err := initListsDeleteCmd(ListsCmd); err != nil {
		return err
	}

	parent.AddCommand(ListsCmd)
	return nil
}
