// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesmessages

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesMessagesGetAttachmentCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "message-id", Shorthand: "m", FieldPath: "MessageID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "attachment-id", Shorthand: "a", FieldPath: "AttachmentID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initInboxesMessagesGetAttachmentCmd initializes the inboxes-messages-get-attachment command.
func initInboxesMessagesGetAttachmentCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-attachment",
		Short:   "Get Attachment",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:messages get-attachment --inbox-id <inbox_id> --message-id <message_id> --attachment-id <attachment_id>\n```",
		Example: "  cli inboxes-messages get-attachment --inbox-id <id> --message-id <id> --attachment-id <id>",
		RunE:    runInboxesMessagesGetAttachmentCmd,
		Aliases: []string{"ga"},
	}
	flagutil.RegisterFlags(cmd, inboxesMessagesGetAttachmentCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesMessagesGetAttachmentRequest](inboxesMessagesGetAttachmentCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-messages-get-attachment: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesMessagesGetAttachmentCmd executes the inboxes-messages-get-attachment command.
func runInboxesMessagesGetAttachmentCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesMessagesGetAttachmentCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesMessagesGetAttachmentCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesMessagesGetAttachmentRequest](cmd, inboxesMessagesGetAttachmentCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesMessagesGetAttachmentServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesMessagesGetAttachmentServerList)-1)
		}
		serverURL := operations.InboxesMessagesGetAttachmentServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InboxesMessages.InboxesMessagesGetAttachment(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
