// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesmessages

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesMessagesDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "message-id", Shorthand: "m", FieldPath: "MessageID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initInboxesMessagesDeleteCmd initializes the inboxes-messages-delete command.
func initInboxesMessagesDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Message",
		Long:    "Permanently deletes a message.\n\n**CLI:**\n```bash\nagentmail inboxes:messages delete --inbox-id <inbox_id> --message-id <message_id>\n```",
		Example: "  agentmail inboxes-messages delete --inbox-id <id> --message-id <id>",
		RunE:    runInboxesMessagesDeleteCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesMessagesDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesMessagesDeleteRequest](inboxesMessagesDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-messages-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesMessagesDeleteCmd executes the inboxes-messages-delete command.
func runInboxesMessagesDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesMessagesDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesMessagesDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesMessagesDeleteRequest](cmd, inboxesMessagesDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesMessagesDeleteServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesMessagesDeleteServerList)-1)
		}
		serverURL := operations.InboxesMessagesDeleteServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InboxesMessages.InboxesMessagesDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
