// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesmessages

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesMessagesForwardCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "message-id", Shorthand: "m", FieldPath: "MessageID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "labels", Shorthand: "l", FieldPath: "Body.Labels", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Labels of message."},
	{FlagName: "reply-to", Shorthand: "r", FieldPath: "Body.ReplyTo", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "to", FieldPath: "Body.To", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "cc", Shorthand: "c", FieldPath: "Body.Cc", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "bcc", Shorthand: "b", FieldPath: "Body.Bcc", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "subject", Shorthand: "s", FieldPath: "Body.Subject", Kind: flagutil.FlagKindString, Optional: true, Description: "Subject of message."},
	{FlagName: "text", FieldPath: "Body.Text", Kind: flagutil.FlagKindString, Optional: true, Description: "Plain text body of message."},
	{FlagName: "html", FieldPath: "Body.HTML", Kind: flagutil.FlagKindString, Optional: true, Description: "HTML body of message."},
	{FlagName: "attachments", Shorthand: "a", FieldPath: "Body.Attachments", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"attachments,omitempty"`, Description: "Attachments to include in message."},
	{FlagName: "headers", FieldPath: "Body.Headers", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"headers,omitempty"`, Description: "Headers to include in message."},
}

// initInboxesMessagesForwardCmd initializes the inboxes-messages-forward command.
func initInboxesMessagesForwardCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "forward",
		Short:   "Forward Message",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:messages forward --inbox-id <inbox_id> --message-id <message_id> --to recipient@example.com\n```",
		Example: "  cli inboxes-messages forward --inbox-id <id> --message-id <id>",
		RunE:    runInboxesMessagesForwardCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesMessagesForwardCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesMessagesForwardRequest](inboxesMessagesForwardCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-messages-forward: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runInboxesMessagesForwardCmd executes the inboxes-messages-forward command.
func runInboxesMessagesForwardCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesMessagesForwardCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesMessagesForwardCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesMessagesForwardRequest](cmd, inboxesMessagesForwardCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesMessagesForwardServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesMessagesForwardServerList)-1)
		}
		serverURL := operations.InboxesMessagesForwardServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InboxesMessages.InboxesMessagesForward(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
