// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesmessages

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInboxesMessagesRoot(parent *cobra.Command) error {
	var InboxesMessagesCmd = &cobra.Command{
		Use:   "inboxes-messages",
		Short: "Operations for inboxes-messages",
		Long:  "Operations for inboxes-messages",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"im"},
	}

	if err := initInboxesMessagesListCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesGetCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesUpdateCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesDeleteCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesGetAttachmentCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesGetRawCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesSendCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesReplyCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesReplyAllCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesForwardCmd(InboxesMessagesCmd); err != nil {
		return err
	}

	parent.AddCommand(InboxesMessagesCmd)
	return nil
}
