workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    api:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: overlays/normalize-tags.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/agentmail/agentmail/api
targets:
    agentmail-cli:
        target: cli
        source: api
    agentmail-python:
        target: python
        source: api
        output: eval/python
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/agentmail/agentmail/api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    agentmail-typescript:
        target: typescript
        source: api
        output: eval/typescript
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/agentmail/agentmail/api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
