// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/components"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var agentVerifyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "otp-code", FieldPath: "OtpCode", Kind: flagutil.FlagKindString, Required: true, Description: "6-digit verification code sent to the human's email address. [required]"},
}

// initAgentVerifyCmd initializes the agent-verify command.
func initAgentVerifyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "verify",
		Short:   "Verify",
		Long:    "Verify an agent organization using the 6-digit OTP sent to the human's email during sign-up.\n\nOn success, the organization is upgraded from `agent_unverified` to `agent_verified`, the send allowlist is removed, and free plan entitlements are applied.\n\nThe OTP expires after 24 hours and allows a maximum of 10 attempts.\n\n**CLI:**\n```bash\nagentmail agent verify --otp-code 123456\n```",
		Example: "  agentmail agent verify --otp-code <value>",
		RunE:    runAgentVerifyCmd,
	}
	flagutil.RegisterFlags(cmd, agentVerifyCmdMeta)
	if err := flagutil.ValidateMeta[components.AgentVerifyRequest](agentVerifyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for agent-verify: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runAgentVerifyCmd executes the agent-verify command.
func runAgentVerifyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, agentVerifyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, agentVerifyCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.AgentVerifyRequest](cmd, agentVerifyCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.AgentVerifyServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.AgentVerifyServerList)-1)
		}
		serverURL := operations.AgentVerifyServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agent.AgentVerify(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
