// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxeslists

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesListsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "direction", FieldPath: "Direction", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"send", "receive", "reply"}, Description: "Direction of list entry. (options: send, receive, reply) [required]"},
	{FlagName: "type", Shorthand: "t", FieldPath: "Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"allow", "block"}, Description: "Type of list entry. (options: allow, block) [required]"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "page-token", Shorthand: "p", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initInboxesListsListCmd initializes the inboxes-lists-list command.
func initInboxesListsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Entries",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:lists list --inbox-id <inbox_id> --direction <direction> --type <type>\n```",
		Example: "  agentmail inboxes-lists list --inbox-id <id> --direction reply --type allow",
		RunE:    runInboxesListsListCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesListsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesListsListRequest](inboxesListsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-lists-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesListsListCmd executes the inboxes-lists-list command.
func runInboxesListsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesListsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesListsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesListsListRequest](cmd, inboxesListsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesListsListServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesListsListServerList)-1)
		}
		serverURL := operations.InboxesListsListServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Lists.InboxesListsList(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
