// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesdrafts

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesDraftsCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "labels", Shorthand: "l", FieldPath: "Body.Labels", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Labels of draft."},
	{FlagName: "reply-to", Shorthand: "r", FieldPath: "Body.ReplyTo", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Reply-to addresses. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "to", FieldPath: "Body.To", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "cc", FieldPath: "Body.Cc", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "bcc", Shorthand: "b", FieldPath: "Body.Bcc", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`."},
	{FlagName: "subject", FieldPath: "Body.Subject", Kind: flagutil.FlagKindString, Optional: true, Description: "Subject of draft."},
	{FlagName: "text", FieldPath: "Body.Text", Kind: flagutil.FlagKindString, Optional: true, Description: "Plain text body of draft."},
	{FlagName: "html", FieldPath: "Body.HTML", Kind: flagutil.FlagKindString, Optional: true, Description: "HTML body of draft."},
	{FlagName: "attachments", Shorthand: "a", FieldPath: "Body.Attachments", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"attachments,omitempty"`, Description: "Attachments to include in draft."},
	{FlagName: "in-reply-to", FieldPath: "Body.InReplyTo", Kind: flagutil.FlagKindString, Optional: true, Description: "ID of message being replied to."},
	{FlagName: "send-at", FieldPath: "Body.SendAt", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "Time at which to schedule send draft."},
	{FlagName: "client-id", FieldPath: "Body.ClientID", Kind: flagutil.FlagKindString, Optional: true, Description: "Client ID of draft."},
}

// initInboxesDraftsCreateCmd initializes the inboxes-drafts-create command.
func initInboxesDraftsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create Draft",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:drafts create --inbox-id <inbox_id> --to recipient@example.com --subject \"Draft subject\" --text \"Draft body\"\n```",
		Example: "  agentmail inboxes-drafts create --inbox-id <id>",
		RunE:    runInboxesDraftsCreateCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesDraftsCreateCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesDraftsCreateRequest](inboxesDraftsCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-drafts-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runInboxesDraftsCreateCmd executes the inboxes-drafts-create command.
func runInboxesDraftsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesDraftsCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesDraftsCreateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesDraftsCreateRequest](cmd, inboxesDraftsCreateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesDraftsCreateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesDraftsCreateServerList)-1)
		}
		serverURL := operations.InboxesDraftsCreateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Drafts.InboxesDraftsCreate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
