// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesdrafts

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesDraftsGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "draft-id", FieldPath: "DraftID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initInboxesDraftsGetCmd initializes the inboxes-drafts-get command.
func initInboxesDraftsGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Draft",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:drafts get --inbox-id <inbox_id> --draft-id <draft_id>\n```",
		Example: "  agentmail inboxes-drafts get --inbox-id <id> --draft-id <id>",
		RunE:    runInboxesDraftsGetCmd,
	}
	flagutil.RegisterFlags(cmd, inboxesDraftsGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesDraftsGetRequest](inboxesDraftsGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-drafts-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesDraftsGetCmd executes the inboxes-drafts-get command.
func runInboxesDraftsGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesDraftsGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesDraftsGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesDraftsGetRequest](cmd, inboxesDraftsGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesDraftsGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesDraftsGetServerList)-1)
		}
		serverURL := operations.InboxesDraftsGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Drafts.InboxesDraftsGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
