// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesdrafts

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInboxesDraftsRoot(parent *cobra.Command) error {
	var InboxesDraftsCmd = &cobra.Command{
		Use:   "drafts",
		Short: "Operations for inboxes-drafts",
		Long:  "Operations for inboxes-drafts",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initInboxesDraftsListCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	if err := initInboxesDraftsCreateCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	if err := initInboxesDraftsGetCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	if err := initInboxesDraftsUpdateCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	if err := initInboxesDraftsDeleteCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	if err := initInboxesDraftsGetAttachmentCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	if err := initInboxesDraftsSendCmd(InboxesDraftsCmd); err != nil {
		return err
	}

	parent.AddCommand(InboxesDraftsCmd)
	return nil
}
