// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package threads

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitThreadsRoot(parent *cobra.Command) error {
	var ThreadsCmd = &cobra.Command{
		Use:   "threads",
		Short: "Operations for threads",
		Long:  "Operations for threads",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initThreadsListCmd(ThreadsCmd); err != nil {
		return err
	}

	if err := initThreadsGetCmd(ThreadsCmd); err != nil {
		return err
	}

	if err := initThreadsUpdateCmd(ThreadsCmd); err != nil {
		return err
	}

	if err := initThreadsDeleteCmd(ThreadsCmd); err != nil {
		return err
	}

	if err := initThreadsGetAttachmentCmd(ThreadsCmd); err != nil {
		return err
	}

	parent.AddCommand(ThreadsCmd)
	return nil
}
