// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package threads

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var threadsGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "thread-id", Shorthand: "t", FieldPath: "ThreadID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initThreadsGetCmd initializes the threads-get command.
func initThreadsGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Thread",
		Long:    "**CLI:**\n```bash\nagentmail threads get --thread-id <thread_id>\n```",
		Example: "  agentmail threads get --thread-id <id>",
		RunE:    runThreadsGetCmd,
	}
	flagutil.RegisterFlags(cmd, threadsGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.ThreadsGetRequest](threadsGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for threads-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runThreadsGetCmd executes the threads-get command.
func runThreadsGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, threadsGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, threadsGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ThreadsGetRequest](cmd, threadsGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.ThreadsGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.ThreadsGetServerList)-1)
		}
		serverURL := operations.ThreadsGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Threads.ThreadsGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
