// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package threads

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var threadsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "thread-id", Shorthand: "t", FieldPath: "ThreadID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "permanent", Shorthand: "p", FieldPath: "Permanent", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=permanent"`, Description: "If true, permanently delete the thread instead of moving to trash."},
}

// initThreadsDeleteCmd initializes the threads-delete command.
func initThreadsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Thread",
		Long:    "Moves the thread to trash by adding a trash label to all messages. If the thread is already in trash, it will be permanently deleted. Use `permanent=true` to force permanent deletion.\n\n**CLI:**\n```bash\nagentmail threads delete --thread-id <thread_id>\n```",
		Example: "  agentmail threads delete --thread-id <id>",
		RunE:    runThreadsDeleteCmd,
	}
	flagutil.RegisterFlags(cmd, threadsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.ThreadsDeleteRequest](threadsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for threads-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runThreadsDeleteCmd executes the threads-delete command.
func runThreadsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, threadsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, threadsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ThreadsDeleteRequest](cmd, threadsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.ThreadsDeleteServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.ThreadsDeleteServerList)-1)
		}
		serverURL := operations.ThreadsDeleteServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Threads.ThreadsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
