// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package domains

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var domainsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "domain-id", FieldPath: "DomainID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "feedback-enabled", Shorthand: "f", FieldPath: "Body.FeedbackEnabled", Kind: flagutil.FlagKindBool, Optional: true, Description: "Bounce and complaint notifications are sent to your inboxes."},
}

// initDomainsUpdateCmd initializes the domains-update command.
func initDomainsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update Domain",
		Long:    "**CLI:**\n```bash\nagentmail domains update --domain-id <domain_id>\n```",
		Example: "  cli domains update --domain-id <id>",
		RunE:    runDomainsUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, domainsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.DomainsUpdateRequest](domainsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for domains-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runDomainsUpdateCmd executes the domains-update command.
func runDomainsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, domainsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, domainsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DomainsUpdateRequest](cmd, domainsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.DomainsUpdateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.DomainsUpdateServerList)-1)
		}
		serverURL := operations.DomainsUpdateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Domains.DomainsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
