// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package domains

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var domainsVerifyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "domain-id", FieldPath: "DomainID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDomainsVerifyCmd initializes the domains-verify command.
func initDomainsVerifyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "verify",
		Short:   "Verify Domain",
		Long:    "**CLI:**\n```bash\nagentmail domains verify --domain-id <domain_id>\n```",
		Example: "  cli domains verify --domain-id <id>",
		RunE:    runDomainsVerifyCmd,
	}
	flagutil.RegisterFlags(cmd, domainsVerifyCmdMeta)
	if err := flagutil.ValidateMeta[operations.DomainsVerifyRequest](domainsVerifyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for domains-verify: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDomainsVerifyCmd executes the domains-verify command.
func runDomainsVerifyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, domainsVerifyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, domainsVerifyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DomainsVerifyRequest](cmd, domainsVerifyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.DomainsVerifyServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.DomainsVerifyServerList)-1)
		}
		serverURL := operations.DomainsVerifyServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Domains.DomainsVerify(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
