// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package podsdomains

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var podsDomainsGetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pod-id", Shorthand: "p", FieldPath: "PodID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "domain-id", FieldPath: "DomainID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initPodsDomainsGetCmd initializes the pods-domains-get command.
func initPodsDomainsGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Domain",
		Long:    "**CLI:**\n```bash\nagentmail pods:domains get --pod-id <pod_id> --domain-id <domain_id>\n```",
		Example: "  agentmail pods-domains get --pod-id <id> --domain-id <id>",
		RunE:    runPodsDomainsGetCmd,
	}
	flagutil.RegisterFlags(cmd, podsDomainsGetCmdMeta)
	if err := flagutil.ValidateMeta[operations.PodsDomainsGetRequest](podsDomainsGetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pods-domains-get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPodsDomainsGetCmd executes the pods-domains-get command.
func runPodsDomainsGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, podsDomainsGetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, podsDomainsGetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PodsDomainsGetRequest](cmd, podsDomainsGetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.PodsDomainsGetServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.PodsDomainsGetServerList)-1)
		}
		serverURL := operations.PodsDomainsGetServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PodsDomains.PodsDomainsGet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
