// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package podsdomains

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var podsDomainsGetZoneFileCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pod-id", Shorthand: "p", FieldPath: "PodID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "domain-id", FieldPath: "DomainID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initPodsDomainsGetZoneFileCmd initializes the pods-domains-get-zone-file command.
func initPodsDomainsGetZoneFileCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-zone-file",
		Short:   "Get Zone File",
		Long:    "**CLI:**\n```bash\nagentmail pods:domains get-zone-file --pod-id <pod_id> --domain-id <domain_id>\n```\n\nThis operation returns binary data. Use --output-file <path> to save to a file, or pipe the output to another command.",
		Example: "  agentmail pods-domains get-zone-file --pod-id <id> --domain-id <id>",
		RunE:    runPodsDomainsGetZoneFileCmd,
		Aliases: []string{"gzf"},
	}
	flagutil.RegisterFlags(cmd, podsDomainsGetZoneFileCmdMeta)
	if err := flagutil.ValidateMeta[operations.PodsDomainsGetZoneFileRequest](podsDomainsGetZoneFileCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pods-domains-get-zone-file: %w", err)
	}
	cmd.Flags().String("output-file", "", "Save the response body to a file path (recommended for binary/file responses)")
	cmd.Flags().Bool("output-b64", false, "Encode binary response as base64 and print to stdout")
	cmd.MarkFlagFilename("output-file")
	parent.AddCommand(cmd)
	return nil
}

// runPodsDomainsGetZoneFileCmd executes the pods-domains-get-zone-file command.
func runPodsDomainsGetZoneFileCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, podsDomainsGetZoneFileCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, podsDomainsGetZoneFileCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PodsDomainsGetZoneFileRequest](cmd, podsDomainsGetZoneFileCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.PodsDomainsGetZoneFileServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.PodsDomainsGetZoneFileServerList)-1)
		}
		serverURL := operations.PodsDomainsGetZoneFileServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	res, err := s.PodsDomains.PodsDomainsGetZoneFile(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}
	if outputFile, _ := flagutil.GetStringFlag(cmd, "output-file"); outputFile != "" {
		return output.WriteToFile(cmd, res, outputFile)
	}
	if outputB64, _ := flagutil.GetBoolFlag(cmd, "output-b64"); outputB64 {
		return output.WriteBase64(cmd, res)
	}
	if output.IsBinaryTTYBlocked(cmd, res) {
		return fmt.Errorf("binary response cannot be written to a terminal; use --output-file <path>, --output-b64, or pipe to another command")
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
