// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesapikeys

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesAPIKeysCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "Name of api key."},
	{FlagName: "permissions", Shorthand: "p", FieldPath: "Body.Permissions", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"permissions,omitempty"`, Description: "Granular permissions for the API key. When ommitted all permissions are granted. Otherwise, only permissions set to true are granted."},
}

// initInboxesApiKeysCreateCmd initializes the inboxes-api-keys-create command.
func initInboxesApiKeysCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "inboxes-api-keys-create",
		Short:   "Create API Key",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:api-keys create --inbox-id <inbox_id> --name \"My Key\"\n```",
		Example: "  agentmail inboxes-API-keys inboxes-api-keys-create --inbox-id <id>",
		RunE:    runInboxesApiKeysCreateCmd,
		Aliases: []string{"iakc"},
	}
	flagutil.RegisterFlags(cmd, inboxesAPIKeysCreateCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesAPIKeysCreateRequest](inboxesAPIKeysCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-api-keys-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runInboxesApiKeysCreateCmd executes the inboxes-api-keys-create command.
func runInboxesApiKeysCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesAPIKeysCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesAPIKeysCreateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesAPIKeysCreateRequest](cmd, inboxesAPIKeysCreateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesAPIKeysCreateServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesAPIKeysCreateServerList)-1)
		}
		serverURL := operations.InboxesAPIKeysCreateServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InboxesAPIKeys.InboxesAPIKeysCreate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
