// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package inboxesapikeys

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInboxesAPIKeysRoot(parent *cobra.Command) error {
	var InboxesAPIKeysCmd = &cobra.Command{
		Use:   "inboxes-API-keys",
		Short: "Operations for inboxes-API-keys",
		Long:  "Operations for inboxes-API-keys",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"iAk"},
	}

	if err := initInboxesApiKeysListCmd(InboxesAPIKeysCmd); err != nil {
		return err
	}

	if err := initInboxesApiKeysCreateCmd(InboxesAPIKeysCmd); err != nil {
		return err
	}

	if err := initInboxesApiKeysDeleteCmd(InboxesAPIKeysCmd); err != nil {
		return err
	}

	parent.AddCommand(InboxesAPIKeysCmd)
	return nil
}
