// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentSignupResponse - Response after successful agent sign-up.
type AgentSignupResponse struct {
	// ID of the created organization.
	OrganizationID string `json:"organization_id"`
	// ID of the auto-created inbox.
	InboxID string `json:"inbox_id"`
	// API key for authenticating subsequent requests. Store this securely, it cannot be retrieved again.
	APIKey string `json:"api_key"`
}

func (a *AgentSignupResponse) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *AgentSignupResponse) GetInboxID() string {
	if a == nil {
		return ""
	}
	return a.InboxID
}

func (a *AgentSignupResponse) GetAPIKey() string {
	if a == nil {
		return ""
	}
	return a.APIKey
}
