// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentSignupRequest - Request body to sign up an agent.
type AgentSignupRequest struct {
	// Email address of the human who owns the agent. A 6-digit OTP will be sent to this address.
	HumanEmail string `json:"human_email"`
	// Username for the auto-created inbox (e.g. "my-agent" creates my-agent@agentmail.to).
	Username string `json:"username"`
}

func (a *AgentSignupRequest) GetHumanEmail() string {
	if a == nil {
		return ""
	}
	return a.HumanEmail
}

func (a *AgentSignupRequest) GetUsername() string {
	if a == nil {
		return ""
	}
	return a.Username
}
