// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentVerifyRequest - Request body to verify an agent with an OTP code.
type AgentVerifyRequest struct {
	// 6-digit verification code sent to the human's email address.
	OtpCode string `json:"otp_code"`
}

func (a *AgentVerifyRequest) GetOtpCode() string {
	if a == nil {
		return ""
	}
	return a.OtpCode
}
