// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentVerifyResponse - Response after successful agent verification.
type AgentVerifyResponse struct {
	// Whether the organization was verified.
	Verified bool `json:"verified"`
}

func (a *AgentVerifyResponse) GetVerified() bool {
	if a == nil {
		return false
	}
	return a.Verified
}
