// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/optionalnullable"
)

// APIKeyPermissions - Granular permissions for the API key. When ommitted all permissions are granted. Otherwise, only permissions set to true are granted.
type APIKeyPermissions struct {
	// Read inbox details.
	InboxRead optionalnullable.OptionalNullable[bool] `json:"inbox_read,omitzero"`
	// Create new inboxes.
	InboxCreate optionalnullable.OptionalNullable[bool] `json:"inbox_create,omitzero"`
	// Update inbox settings.
	InboxUpdate optionalnullable.OptionalNullable[bool] `json:"inbox_update,omitzero"`
	// Delete inboxes.
	InboxDelete optionalnullable.OptionalNullable[bool] `json:"inbox_delete,omitzero"`
	// Read threads.
	ThreadRead optionalnullable.OptionalNullable[bool] `json:"thread_read,omitzero"`
	// Delete threads.
	ThreadDelete optionalnullable.OptionalNullable[bool] `json:"thread_delete,omitzero"`
	// Read messages.
	MessageRead optionalnullable.OptionalNullable[bool] `json:"message_read,omitzero"`
	// Send messages.
	MessageSend optionalnullable.OptionalNullable[bool] `json:"message_send,omitzero"`
	// Update message labels.
	MessageUpdate optionalnullable.OptionalNullable[bool] `json:"message_update,omitzero"`
	// Access messages labeled spam.
	LabelSpamRead optionalnullable.OptionalNullable[bool] `json:"label_spam_read,omitzero"`
	// Access messages labeled blocked.
	LabelBlockedRead optionalnullable.OptionalNullable[bool] `json:"label_blocked_read,omitzero"`
	// Access messages labeled trash.
	LabelTrashRead optionalnullable.OptionalNullable[bool] `json:"label_trash_read,omitzero"`
	// Read drafts.
	DraftRead optionalnullable.OptionalNullable[bool] `json:"draft_read,omitzero"`
	// Create drafts.
	DraftCreate optionalnullable.OptionalNullable[bool] `json:"draft_create,omitzero"`
	// Update drafts.
	DraftUpdate optionalnullable.OptionalNullable[bool] `json:"draft_update,omitzero"`
	// Delete drafts.
	DraftDelete optionalnullable.OptionalNullable[bool] `json:"draft_delete,omitzero"`
	// Send drafts.
	DraftSend optionalnullable.OptionalNullable[bool] `json:"draft_send,omitzero"`
	// Read webhook configurations.
	WebhookRead optionalnullable.OptionalNullable[bool] `json:"webhook_read,omitzero"`
	// Create webhooks.
	WebhookCreate optionalnullable.OptionalNullable[bool] `json:"webhook_create,omitzero"`
	// Update webhooks.
	WebhookUpdate optionalnullable.OptionalNullable[bool] `json:"webhook_update,omitzero"`
	// Delete webhooks.
	WebhookDelete optionalnullable.OptionalNullable[bool] `json:"webhook_delete,omitzero"`
	// Read domain details.
	DomainRead optionalnullable.OptionalNullable[bool] `json:"domain_read,omitzero"`
	// Create domains.
	DomainCreate optionalnullable.OptionalNullable[bool] `json:"domain_create,omitzero"`
	// Update domains.
	DomainUpdate optionalnullable.OptionalNullable[bool] `json:"domain_update,omitzero"`
	// Delete domains.
	DomainDelete optionalnullable.OptionalNullable[bool] `json:"domain_delete,omitzero"`
	// Read list entries.
	ListEntryRead optionalnullable.OptionalNullable[bool] `json:"list_entry_read,omitzero"`
	// Create list entries.
	ListEntryCreate optionalnullable.OptionalNullable[bool] `json:"list_entry_create,omitzero"`
	// Delete list entries.
	ListEntryDelete optionalnullable.OptionalNullable[bool] `json:"list_entry_delete,omitzero"`
	// Read metrics.
	MetricsRead optionalnullable.OptionalNullable[bool] `json:"metrics_read,omitzero"`
	// Read API keys.
	APIKeyRead optionalnullable.OptionalNullable[bool] `json:"api_key_read,omitzero"`
	// Create API keys.
	APIKeyCreate optionalnullable.OptionalNullable[bool] `json:"api_key_create,omitzero"`
	// Delete API keys.
	APIKeyDelete optionalnullable.OptionalNullable[bool] `json:"api_key_delete,omitzero"`
	// Read pods.
	PodRead optionalnullable.OptionalNullable[bool] `json:"pod_read,omitzero"`
	// Create pods.
	PodCreate optionalnullable.OptionalNullable[bool] `json:"pod_create,omitzero"`
	// Delete pods.
	PodDelete optionalnullable.OptionalNullable[bool] `json:"pod_delete,omitzero"`
}

func (a *APIKeyPermissions) GetInboxRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.InboxRead
}

func (a *APIKeyPermissions) GetInboxCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.InboxCreate
}

func (a *APIKeyPermissions) GetInboxUpdate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.InboxUpdate
}

func (a *APIKeyPermissions) GetInboxDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.InboxDelete
}

func (a *APIKeyPermissions) GetThreadRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.ThreadRead
}

func (a *APIKeyPermissions) GetThreadDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.ThreadDelete
}

func (a *APIKeyPermissions) GetMessageRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.MessageRead
}

func (a *APIKeyPermissions) GetMessageSend() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.MessageSend
}

func (a *APIKeyPermissions) GetMessageUpdate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.MessageUpdate
}

func (a *APIKeyPermissions) GetLabelSpamRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.LabelSpamRead
}

func (a *APIKeyPermissions) GetLabelBlockedRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.LabelBlockedRead
}

func (a *APIKeyPermissions) GetLabelTrashRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.LabelTrashRead
}

func (a *APIKeyPermissions) GetDraftRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DraftRead
}

func (a *APIKeyPermissions) GetDraftCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DraftCreate
}

func (a *APIKeyPermissions) GetDraftUpdate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DraftUpdate
}

func (a *APIKeyPermissions) GetDraftDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DraftDelete
}

func (a *APIKeyPermissions) GetDraftSend() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DraftSend
}

func (a *APIKeyPermissions) GetWebhookRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.WebhookRead
}

func (a *APIKeyPermissions) GetWebhookCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.WebhookCreate
}

func (a *APIKeyPermissions) GetWebhookUpdate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.WebhookUpdate
}

func (a *APIKeyPermissions) GetWebhookDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.WebhookDelete
}

func (a *APIKeyPermissions) GetDomainRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DomainRead
}

func (a *APIKeyPermissions) GetDomainCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DomainCreate
}

func (a *APIKeyPermissions) GetDomainUpdate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DomainUpdate
}

func (a *APIKeyPermissions) GetDomainDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.DomainDelete
}

func (a *APIKeyPermissions) GetListEntryRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.ListEntryRead
}

func (a *APIKeyPermissions) GetListEntryCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.ListEntryCreate
}

func (a *APIKeyPermissions) GetListEntryDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.ListEntryDelete
}

func (a *APIKeyPermissions) GetMetricsRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.MetricsRead
}

func (a *APIKeyPermissions) GetAPIKeyRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.APIKeyRead
}

func (a *APIKeyPermissions) GetAPIKeyCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.APIKeyCreate
}

func (a *APIKeyPermissions) GetAPIKeyDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.APIKeyDelete
}

func (a *APIKeyPermissions) GetPodRead() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.PodRead
}

func (a *APIKeyPermissions) GetPodCreate() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.PodCreate
}

func (a *APIKeyPermissions) GetPodDelete() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.PodDelete
}
