// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/optionalnullable"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type CreateDraftRequest struct {
	// Labels of draft.
	Labels []string `json:"labels,omitzero"`
	// Reply-to addresses. In format `username@domain.com` or `Display Name <username@domain.com>`.
	ReplyTo []string `json:"reply_to,omitzero"`
	// Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	To []string `json:"to,omitzero"`
	// Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Cc []string `json:"cc,omitzero"`
	// Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Bcc []string `json:"bcc,omitzero"`
	// Subject of draft.
	Subject *string `json:"subject,omitzero"`
	// Plain text body of draft.
	Text *string `json:"text,omitzero"`
	// HTML body of draft.
	HTML *string `json:"html,omitzero"`
	// Attachments to include in draft.
	Attachments optionalnullable.OptionalNullable[[]SendAttachment] `json:"attachments,omitzero"`
	// ID of message being replied to.
	InReplyTo *string `json:"in_reply_to,omitzero"`
	// Time at which to schedule send draft.
	SendAt *time.Time `json:"send_at,omitzero"`
	// Client ID of draft.
	ClientID *string `json:"client_id,omitzero"`
}

func (c CreateDraftRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDraftRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDraftRequest) GetLabels() []string {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *CreateDraftRequest) GetReplyTo() []string {
	if c == nil {
		return nil
	}
	return c.ReplyTo
}

func (c *CreateDraftRequest) GetTo() []string {
	if c == nil {
		return nil
	}
	return c.To
}

func (c *CreateDraftRequest) GetCc() []string {
	if c == nil {
		return nil
	}
	return c.Cc
}

func (c *CreateDraftRequest) GetBcc() []string {
	if c == nil {
		return nil
	}
	return c.Bcc
}

func (c *CreateDraftRequest) GetSubject() *string {
	if c == nil {
		return nil
	}
	return c.Subject
}

func (c *CreateDraftRequest) GetText() *string {
	if c == nil {
		return nil
	}
	return c.Text
}

func (c *CreateDraftRequest) GetHTML() *string {
	if c == nil {
		return nil
	}
	return c.HTML
}

func (c *CreateDraftRequest) GetAttachments() optionalnullable.OptionalNullable[[]SendAttachment] {
	if c == nil {
		return nil
	}
	return c.Attachments
}

func (c *CreateDraftRequest) GetInReplyTo() *string {
	if c == nil {
		return nil
	}
	return c.InReplyTo
}

func (c *CreateDraftRequest) GetSendAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.SendAt
}

func (c *CreateDraftRequest) GetClientID() *string {
	if c == nil {
		return nil
	}
	return c.ClientID
}
