// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDomainRequest struct {
	// The name of the domain (e.g., `example.com`).
	Domain string `json:"domain"`
	// Bounce and complaint notifications are sent to your inboxes.
	FeedbackEnabled bool `json:"feedback_enabled"`
}

func (c *CreateDomainRequest) GetDomain() string {
	if c == nil {
		return ""
	}
	return c.Domain
}

func (c *CreateDomainRequest) GetFeedbackEnabled() bool {
	if c == nil {
		return false
	}
	return c.FeedbackEnabled
}
