// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/optionalnullable"
)

type CreateListEntryRequest struct {
	// Email address or domain to add.
	Entry string `json:"entry"`
	// Reason for adding the entry.
	Reason optionalnullable.OptionalNullable[string] `json:"reason,omitzero"`
}

func (c *CreateListEntryRequest) GetEntry() string {
	if c == nil {
		return ""
	}
	return c.Entry
}

func (c *CreateListEntryRequest) GetReason() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Reason
}
