// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Direction of list entry.
type Direction string

const (
	DirectionSend    Direction = "send"
	DirectionReceive Direction = "receive"
	DirectionReply   Direction = "reply"
)

func (e Direction) ToPointer() *Direction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Direction) IsExact() bool {
	if e != nil {
		switch *e {
		case "send", "receive", "reply":
			return true
		}
	}
	return false
}
