// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type Domain struct {
	// ID of pod.
	PodID *string `json:"pod_id,omitzero"`
	// The ID of the domain.
	DomainID string `json:"domain_id"`
	// The name of the domain (e.g., `example.com`).
	Domain string `json:"domain"`
	Status Status `json:"status"`
	// Bounce and complaint notifications are sent to your inboxes.
	FeedbackEnabled bool `json:"feedback_enabled"`
	// A list of DNS records required to verify the domain.
	Records []VerificationRecord `json:"records"`
	// Client ID of domain.
	ClientID *string `json:"client_id,omitzero"`
	// Time at which the domain was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Time at which the domain was created.
	CreatedAt time.Time `json:"created_at"`
}

func (d Domain) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Domain) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *Domain) GetPodID() *string {
	if d == nil {
		return nil
	}
	return d.PodID
}

func (d *Domain) GetDomainID() string {
	if d == nil {
		return ""
	}
	return d.DomainID
}

func (d *Domain) GetDomain() string {
	if d == nil {
		return ""
	}
	return d.Domain
}

func (d *Domain) GetStatus() Status {
	if d == nil {
		return Status("")
	}
	return d.Status
}

func (d *Domain) GetFeedbackEnabled() bool {
	if d == nil {
		return false
	}
	return d.FeedbackEnabled
}

func (d *Domain) GetRecords() []VerificationRecord {
	if d == nil {
		return []VerificationRecord{}
	}
	return d.Records
}

func (d *Domain) GetClientID() *string {
	if d == nil {
		return nil
	}
	return d.ClientID
}

func (d *Domain) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *Domain) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}
