// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/optionalnullable"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type Draft struct {
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// ID of draft.
	DraftID string `json:"draft_id"`
	// Client ID of draft.
	ClientID *string `json:"client_id,omitzero"`
	// Labels of draft.
	Labels []string `json:"labels"`
	// Reply-to addresses. In format `username@domain.com` or `Display Name <username@domain.com>`.
	ReplyTo []string `json:"reply_to,omitzero"`
	// Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	To []string `json:"to,omitzero"`
	// Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Cc []string `json:"cc,omitzero"`
	// Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Bcc []string `json:"bcc,omitzero"`
	// Subject of draft.
	Subject *string `json:"subject,omitzero"`
	// Text preview of draft.
	Preview *string `json:"preview,omitzero"`
	// Plain text body of draft.
	Text *string `json:"text,omitzero"`
	// HTML body of draft.
	HTML *string `json:"html,omitzero"`
	// Attachments in draft.
	Attachments []Attachment `json:"attachments,omitzero"`
	// ID of message being replied to.
	InReplyTo *string `json:"in_reply_to,omitzero"`
	// IDs of previous messages in thread.
	References optionalnullable.OptionalNullable[[]string] `json:"references,omitzero"`
	// Schedule send status of draft.
	SendStatus *DraftSendStatus `json:"send_status,omitzero"`
	// Time at which to schedule send draft.
	SendAt *time.Time `json:"send_at,omitzero"`
	// Time at which draft was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Time at which draft was created.
	CreatedAt time.Time `json:"created_at"`
}

func (d Draft) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Draft) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *Draft) GetInboxID() string {
	if d == nil {
		return ""
	}
	return d.InboxID
}

func (d *Draft) GetDraftID() string {
	if d == nil {
		return ""
	}
	return d.DraftID
}

func (d *Draft) GetClientID() *string {
	if d == nil {
		return nil
	}
	return d.ClientID
}

func (d *Draft) GetLabels() []string {
	if d == nil {
		return []string{}
	}
	return d.Labels
}

func (d *Draft) GetReplyTo() []string {
	if d == nil {
		return nil
	}
	return d.ReplyTo
}

func (d *Draft) GetTo() []string {
	if d == nil {
		return nil
	}
	return d.To
}

func (d *Draft) GetCc() []string {
	if d == nil {
		return nil
	}
	return d.Cc
}

func (d *Draft) GetBcc() []string {
	if d == nil {
		return nil
	}
	return d.Bcc
}

func (d *Draft) GetSubject() *string {
	if d == nil {
		return nil
	}
	return d.Subject
}

func (d *Draft) GetPreview() *string {
	if d == nil {
		return nil
	}
	return d.Preview
}

func (d *Draft) GetText() *string {
	if d == nil {
		return nil
	}
	return d.Text
}

func (d *Draft) GetHTML() *string {
	if d == nil {
		return nil
	}
	return d.HTML
}

func (d *Draft) GetAttachments() []Attachment {
	if d == nil {
		return nil
	}
	return d.Attachments
}

func (d *Draft) GetInReplyTo() *string {
	if d == nil {
		return nil
	}
	return d.InReplyTo
}

func (d *Draft) GetReferences() optionalnullable.OptionalNullable[[]string] {
	if d == nil {
		return nil
	}
	return d.References
}

func (d *Draft) GetSendStatus() *DraftSendStatus {
	if d == nil {
		return nil
	}
	return d.SendStatus
}

func (d *Draft) GetSendAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.SendAt
}

func (d *Draft) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *Draft) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}
