// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type DraftItem struct {
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// ID of draft.
	DraftID string `json:"draft_id"`
	// Labels of draft.
	Labels []string `json:"labels"`
	// Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	To []string `json:"to,omitzero"`
	// Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Cc []string `json:"cc,omitzero"`
	// Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Bcc []string `json:"bcc,omitzero"`
	// Subject of draft.
	Subject *string `json:"subject,omitzero"`
	// Text preview of draft.
	Preview *string `json:"preview,omitzero"`
	// Attachments in draft.
	Attachments []Attachment `json:"attachments,omitzero"`
	// ID of message being replied to.
	InReplyTo *string `json:"in_reply_to,omitzero"`
	// Schedule send status of draft.
	SendStatus *DraftSendStatus `json:"send_status,omitzero"`
	// Time at which to schedule send draft.
	SendAt *time.Time `json:"send_at,omitzero"`
	// Time at which draft was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (d DraftItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DraftItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DraftItem) GetInboxID() string {
	if d == nil {
		return ""
	}
	return d.InboxID
}

func (d *DraftItem) GetDraftID() string {
	if d == nil {
		return ""
	}
	return d.DraftID
}

func (d *DraftItem) GetLabels() []string {
	if d == nil {
		return []string{}
	}
	return d.Labels
}

func (d *DraftItem) GetTo() []string {
	if d == nil {
		return nil
	}
	return d.To
}

func (d *DraftItem) GetCc() []string {
	if d == nil {
		return nil
	}
	return d.Cc
}

func (d *DraftItem) GetBcc() []string {
	if d == nil {
		return nil
	}
	return d.Bcc
}

func (d *DraftItem) GetSubject() *string {
	if d == nil {
		return nil
	}
	return d.Subject
}

func (d *DraftItem) GetPreview() *string {
	if d == nil {
		return nil
	}
	return d.Preview
}

func (d *DraftItem) GetAttachments() []Attachment {
	if d == nil {
		return nil
	}
	return d.Attachments
}

func (d *DraftItem) GetInReplyTo() *string {
	if d == nil {
		return nil
	}
	return d.InReplyTo
}

func (d *DraftItem) GetSendStatus() *DraftSendStatus {
	if d == nil {
		return nil
	}
	return d.SendStatus
}

func (d *DraftItem) GetSendAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.SendAt
}

func (d *DraftItem) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}
