// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InboxesListInboxesResponse struct {
	// Number of items returned.
	Count int64 `json:"count"`
	// Limit of number of items returned.
	Limit *int64 `json:"limit,omitzero"`
	// Page token for pagination.
	NextPageToken *string `json:"next_page_token,omitzero"`
	// Ordered by `created_at` descending.
	Inboxes []InboxesInbox `json:"inboxes"`
}

func (i *InboxesListInboxesResponse) GetCount() int64 {
	if i == nil {
		return 0
	}
	return i.Count
}

func (i *InboxesListInboxesResponse) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *InboxesListInboxesResponse) GetNextPageToken() *string {
	if i == nil {
		return nil
	}
	return i.NextPageToken
}

func (i *InboxesListInboxesResponse) GetInboxes() []InboxesInbox {
	if i == nil {
		return []InboxesInbox{}
	}
	return i.Inboxes
}
