// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// InboxEventType - Type of inbox event.
type InboxEventType string

const (
	InboxEventTypeLabelAdded   InboxEventType = "label_added"
	InboxEventTypeLabelRemoved InboxEventType = "label_removed"
)

func (e InboxEventType) ToPointer() *InboxEventType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InboxEventType) IsExact() bool {
	if e != nil {
		switch *e {
		case "label_added", "label_removed":
			return true
		}
	}
	return false
}
