// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type InboxesInbox struct {
	// ID of pod.
	PodID string `json:"pod_id"`
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// Email address of the inbox.
	Email string `json:"email"`
	// Display name: `Display Name <username@domain.com>`.
	DisplayName *string `json:"display_name,omitzero"`
	// Client ID of inbox.
	ClientID *string `json:"client_id,omitzero"`
	// Time at which inbox was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Time at which inbox was created.
	CreatedAt time.Time `json:"created_at"`
}

func (i InboxesInbox) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxesInbox) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxesInbox) GetPodID() string {
	if i == nil {
		return ""
	}
	return i.PodID
}

func (i *InboxesInbox) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxesInbox) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *InboxesInbox) GetDisplayName() *string {
	if i == nil {
		return nil
	}
	return i.DisplayName
}

func (i *InboxesInbox) GetClientID() *string {
	if i == nil {
		return nil
	}
	return i.ClientID
}

func (i *InboxesInbox) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *InboxesInbox) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}
