// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type InboxEvent struct {
	// ID of organization.
	OrganizationID string `json:"organization_id"`
	// ID of pod.
	PodID string `json:"pod_id"`
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// ID of event.
	EventID string `json:"event_id"`
	// Type of inbox event.
	EventType InboxEventType `json:"event_type"`
	// ID of message.
	MessageID string `json:"message_id"`
	// Label added or removed.
	Label string `json:"label"`
	// Time at which the event occurred.
	EventAt time.Time `json:"event_at"`
	// Time at which the event was recorded.
	CreatedAt time.Time `json:"created_at"`
}

func (i InboxEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InboxEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InboxEvent) GetOrganizationID() string {
	if i == nil {
		return ""
	}
	return i.OrganizationID
}

func (i *InboxEvent) GetPodID() string {
	if i == nil {
		return ""
	}
	return i.PodID
}

func (i *InboxEvent) GetInboxID() string {
	if i == nil {
		return ""
	}
	return i.InboxID
}

func (i *InboxEvent) GetEventID() string {
	if i == nil {
		return ""
	}
	return i.EventID
}

func (i *InboxEvent) GetEventType() InboxEventType {
	if i == nil {
		return InboxEventType("")
	}
	return i.EventType
}

func (i *InboxEvent) GetMessageID() string {
	if i == nil {
		return ""
	}
	return i.MessageID
}

func (i *InboxEvent) GetLabel() string {
	if i == nil {
		return ""
	}
	return i.Label
}

func (i *InboxEvent) GetEventAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.EventAt
}

func (i *InboxEvent) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}
