// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListInboxEventsResponse struct {
	// Number of items returned.
	Count int64 `json:"count"`
	// Limit of number of items returned.
	Limit *int64 `json:"limit,omitzero"`
	// Page token for pagination.
	NextPageToken *string `json:"next_page_token,omitzero"`
	// Ordered by `event_id` descending.
	Events []InboxEvent `json:"events"`
}

func (l *ListInboxEventsResponse) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListInboxEventsResponse) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListInboxEventsResponse) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}

func (l *ListInboxEventsResponse) GetEvents() []InboxEvent {
	if l == nil {
		return []InboxEvent{}
	}
	return l.Events
}
