// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListThreadsResponse struct {
	// Number of items returned.
	Count int64 `json:"count"`
	// Limit of number of items returned.
	Limit *int64 `json:"limit,omitzero"`
	// Page token for pagination.
	NextPageToken *string `json:"next_page_token,omitzero"`
	// Ordered by `timestamp` descending.
	Threads []ThreadItem `json:"threads"`
}

func (l *ListThreadsResponse) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListThreadsResponse) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListThreadsResponse) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}

func (l *ListThreadsResponse) GetThreads() []ThreadItem {
	if l == nil {
		return []ThreadItem{}
	}
	return l.Threads
}
