// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListType - Type of list entry.
type ListType string

const (
	ListTypeAllow ListType = "allow"
	ListTypeBlock ListType = "block"
)

func (e ListType) ToPointer() *ListType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ListType) IsExact() bool {
	if e != nil {
		switch *e {
		case "allow", "block":
			return true
		}
	}
	return false
}
