// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListDomainsResponse struct {
	// Number of items returned.
	Count int64 `json:"count"`
	// Limit of number of items returned.
	Limit *int64 `json:"limit,omitzero"`
	// Page token for pagination.
	NextPageToken *string `json:"next_page_token,omitzero"`
	// Ordered by `created_at` descending.
	Domains []DomainItem `json:"domains"`
}

func (l *ListDomainsResponse) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListDomainsResponse) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListDomainsResponse) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}

func (l *ListDomainsResponse) GetDomains() []DomainItem {
	if l == nil {
		return []DomainItem{}
	}
	return l.Domains
}
