// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type MessageItem struct {
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// ID of thread.
	ThreadID string `json:"thread_id"`
	// ID of message.
	MessageID string `json:"message_id"`
	// Labels of message.
	Labels []string `json:"labels"`
	// Time at which message was sent or drafted.
	Timestamp time.Time `json:"timestamp"`
	// Address of sender. In format `username@domain.com` or `Display Name <username@domain.com>`.
	From string `json:"from"`
	// Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	To []string `json:"to"`
	// Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Cc []string `json:"cc,omitzero"`
	// Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Bcc []string `json:"bcc,omitzero"`
	// Subject of message.
	Subject *string `json:"subject,omitzero"`
	// Text preview of message.
	Preview *string `json:"preview,omitzero"`
	// Attachments in message.
	Attachments []Attachment `json:"attachments,omitzero"`
	// ID of message being replied to.
	InReplyTo *string `json:"in_reply_to,omitzero"`
	// IDs of previous messages in thread.
	References []string `json:"references,omitzero"`
	// Headers in message.
	Headers map[string]string `json:"headers,omitzero"`
	// Size of message in bytes.
	Size int64 `json:"size"`
	// Time at which message was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Time at which message was created.
	CreatedAt time.Time `json:"created_at"`
}

func (m MessageItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessageItem) GetInboxID() string {
	if m == nil {
		return ""
	}
	return m.InboxID
}

func (m *MessageItem) GetThreadID() string {
	if m == nil {
		return ""
	}
	return m.ThreadID
}

func (m *MessageItem) GetMessageID() string {
	if m == nil {
		return ""
	}
	return m.MessageID
}

func (m *MessageItem) GetLabels() []string {
	if m == nil {
		return []string{}
	}
	return m.Labels
}

func (m *MessageItem) GetTimestamp() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.Timestamp
}

func (m *MessageItem) GetFrom() string {
	if m == nil {
		return ""
	}
	return m.From
}

func (m *MessageItem) GetTo() []string {
	if m == nil {
		return []string{}
	}
	return m.To
}

func (m *MessageItem) GetCc() []string {
	if m == nil {
		return nil
	}
	return m.Cc
}

func (m *MessageItem) GetBcc() []string {
	if m == nil {
		return nil
	}
	return m.Bcc
}

func (m *MessageItem) GetSubject() *string {
	if m == nil {
		return nil
	}
	return m.Subject
}

func (m *MessageItem) GetPreview() *string {
	if m == nil {
		return nil
	}
	return m.Preview
}

func (m *MessageItem) GetAttachments() []Attachment {
	if m == nil {
		return nil
	}
	return m.Attachments
}

func (m *MessageItem) GetInReplyTo() *string {
	if m == nil {
		return nil
	}
	return m.InReplyTo
}

func (m *MessageItem) GetReferences() []string {
	if m == nil {
		return nil
	}
	return m.References
}

func (m *MessageItem) GetHeaders() map[string]string {
	if m == nil {
		return nil
	}
	return m.Headers
}

func (m *MessageItem) GetSize() int64 {
	if m == nil {
		return 0
	}
	return m.Size
}

func (m *MessageItem) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *MessageItem) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}
