// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// MetricEventType - Type of metric event.
type MetricEventType string

const (
	MetricEventTypeMessageSent       MetricEventType = "message.sent"
	MetricEventTypeMessageDelivered  MetricEventType = "message.delivered"
	MetricEventTypeMessageBounced    MetricEventType = "message.bounced"
	MetricEventTypeMessageDelayed    MetricEventType = "message.delayed"
	MetricEventTypeMessageRejected   MetricEventType = "message.rejected"
	MetricEventTypeMessageComplained MetricEventType = "message.complained"
	MetricEventTypeMessageReceived   MetricEventType = "message.received"
)

func (e MetricEventType) ToPointer() *MetricEventType {
	return &e
}
func (e *MetricEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "message.sent":
		fallthrough
	case "message.delivered":
		fallthrough
	case "message.bounced":
		fallthrough
	case "message.delayed":
		fallthrough
	case "message.rejected":
		fallthrough
	case "message.complained":
		fallthrough
	case "message.received":
		*e = MetricEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricEventType: %v", v)
	}
}
