// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/optionalnullable"
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type PodListEntry struct {
	// Email address or domain of list entry.
	Entry string `json:"entry"`
	// ID of organization.
	OrganizationID string `json:"organization_id"`
	// Reason for adding the entry.
	Reason optionalnullable.OptionalNullable[string] `json:"reason,omitzero"`
	// Direction of list entry.
	Direction Direction `json:"direction"`
	// Type of list entry.
	ListType ListType `json:"list_type"`
	// Whether the entry is an email address or domain.
	EntryType EntryType `json:"entry_type"`
	// Time at which entry was created.
	CreatedAt time.Time `json:"created_at"`
	// ID of pod.
	PodID string `json:"pod_id"`
	// ID of inbox, if entry is inbox-scoped.
	InboxID optionalnullable.OptionalNullable[string] `json:"inbox_id,omitzero"`
}

func (p PodListEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PodListEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PodListEntry) GetEntry() string {
	if p == nil {
		return ""
	}
	return p.Entry
}

func (p *PodListEntry) GetOrganizationID() string {
	if p == nil {
		return ""
	}
	return p.OrganizationID
}

func (p *PodListEntry) GetReason() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Reason
}

func (p *PodListEntry) GetDirection() Direction {
	if p == nil {
		return Direction("")
	}
	return p.Direction
}

func (p *PodListEntry) GetListType() ListType {
	if p == nil {
		return ListType("")
	}
	return p.ListType
}

func (p *PodListEntry) GetEntryType() EntryType {
	if p == nil {
		return EntryType("")
	}
	return p.EntryType
}

func (p *PodListEntry) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PodListEntry) GetPodID() string {
	if p == nil {
		return ""
	}
	return p.PodID
}

func (p *PodListEntry) GetInboxID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.InboxID
}
