// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PodsCreatePodRequest struct {
	// Name of pod.
	Name *string `json:"name,omitzero"`
	// Client ID of pod.
	ClientID *string `json:"client_id,omitzero"`
}

func (p *PodsCreatePodRequest) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PodsCreatePodRequest) GetClientID() *string {
	if p == nil {
		return nil
	}
	return p.ClientID
}
