// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PodsListPodsResponse struct {
	// Number of items returned.
	Count int64 `json:"count"`
	// Limit of number of items returned.
	Limit *int64 `json:"limit,omitzero"`
	// Page token for pagination.
	NextPageToken *string `json:"next_page_token,omitzero"`
	// Ordered by `created_at` descending.
	Pods []PodsPod `json:"pods"`
}

func (p *PodsListPodsResponse) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}

func (p *PodsListPodsResponse) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PodsListPodsResponse) GetNextPageToken() *string {
	if p == nil {
		return nil
	}
	return p.NextPageToken
}

func (p *PodsListPodsResponse) GetPods() []PodsPod {
	if p == nil {
		return []PodsPod{}
	}
	return p.Pods
}
