// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecordStatus string

const (
	RecordStatusMissing RecordStatus = "MISSING"
	RecordStatusInvalid RecordStatus = "INVALID"
	RecordStatusValid   RecordStatus = "VALID"
)

func (e RecordStatus) ToPointer() *RecordStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RecordStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "MISSING", "INVALID", "VALID":
			return true
		}
	}
	return false
}
