// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SendMessageResponse struct {
	// ID of message.
	MessageID string `json:"message_id"`
	// ID of thread.
	ThreadID string `json:"thread_id"`
}

func (s *SendMessageResponse) GetMessageID() string {
	if s == nil {
		return ""
	}
	return s.MessageID
}

func (s *SendMessageResponse) GetThreadID() string {
	if s == nil {
		return ""
	}
	return s.ThreadID
}
