// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"errors"
	"fmt"
)

type SendMessageReplyToType string

const (
	SendMessageReplyToTypeStr        SendMessageReplyToType = "str"
	SendMessageReplyToTypeArrayOfStr SendMessageReplyToType = "arrayOfStr"
)

type SendMessageReplyTo struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type SendMessageReplyToType
}

func CreateSendMessageReplyToStr(str string) SendMessageReplyTo {
	typ := SendMessageReplyToTypeStr

	return SendMessageReplyTo{
		Str:  &str,
		Type: typ,
	}
}

func CreateSendMessageReplyToArrayOfStr(arrayOfStr []string) SendMessageReplyTo {
	typ := SendMessageReplyToTypeArrayOfStr

	return SendMessageReplyTo{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *SendMessageReplyTo) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SendMessageReplyToTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SendMessageReplyToTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendMessageReplyTo", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendMessageReplyTo", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SendMessageReplyToType)
	switch best.Type {
	case SendMessageReplyToTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case SendMessageReplyToTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendMessageReplyTo", string(data))
}

func (u SendMessageReplyTo) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type SendMessageReplyTo: all fields are null")
}
