// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"errors"
	"fmt"
)

type SendMessageBccType string

const (
	SendMessageBccTypeStr        SendMessageBccType = "str"
	SendMessageBccTypeArrayOfStr SendMessageBccType = "arrayOfStr"
)

type SendMessageBcc struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type SendMessageBccType
}

func CreateSendMessageBccStr(str string) SendMessageBcc {
	typ := SendMessageBccTypeStr

	return SendMessageBcc{
		Str:  &str,
		Type: typ,
	}
}

func CreateSendMessageBccArrayOfStr(arrayOfStr []string) SendMessageBcc {
	typ := SendMessageBccTypeArrayOfStr

	return SendMessageBcc{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *SendMessageBcc) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SendMessageBccTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SendMessageBccTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendMessageBcc", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendMessageBcc", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SendMessageBccType)
	switch best.Type {
	case SendMessageBccTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case SendMessageBccTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendMessageBcc", string(data))
}

func (u SendMessageBcc) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type SendMessageBcc: all fields are null")
}
