// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
)

type SendMessageRequest struct {
	// Labels of message.
	Labels  []string            `json:"labels,omitzero"`
	ReplyTo *SendMessageReplyTo `json:"reply_to,omitzero"`
	To      *SendMessageTo      `json:"to,omitzero"`
	Cc      *SendMessageCc      `json:"cc,omitzero"`
	Bcc     *SendMessageBcc     `json:"bcc,omitzero"`
	// Subject of message.
	Subject *string `json:"subject,omitzero"`
	// Plain text body of message.
	Text *string `json:"text,omitzero"`
	// HTML body of message.
	HTML *string `json:"html,omitzero"`
	// Attachments to include in message.
	Attachments []SendAttachment `json:"attachments,omitzero"`
	// Headers to include in message.
	Headers map[string]string `json:"headers,omitzero"`
}

func (s SendMessageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SendMessageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SendMessageRequest) GetLabels() []string {
	if s == nil {
		return nil
	}
	return s.Labels
}

func (s *SendMessageRequest) GetReplyTo() *SendMessageReplyTo {
	if s == nil {
		return nil
	}
	return s.ReplyTo
}

func (s *SendMessageRequest) GetTo() *SendMessageTo {
	if s == nil {
		return nil
	}
	return s.To
}

func (s *SendMessageRequest) GetCc() *SendMessageCc {
	if s == nil {
		return nil
	}
	return s.Cc
}

func (s *SendMessageRequest) GetBcc() *SendMessageBcc {
	if s == nil {
		return nil
	}
	return s.Bcc
}

func (s *SendMessageRequest) GetSubject() *string {
	if s == nil {
		return nil
	}
	return s.Subject
}

func (s *SendMessageRequest) GetText() *string {
	if s == nil {
		return nil
	}
	return s.Text
}

func (s *SendMessageRequest) GetHTML() *string {
	if s == nil {
		return nil
	}
	return s.HTML
}

func (s *SendMessageRequest) GetAttachments() []SendAttachment {
	if s == nil {
		return nil
	}
	return s.Attachments
}

func (s *SendMessageRequest) GetHeaders() map[string]string {
	if s == nil {
		return nil
	}
	return s.Headers
}
