// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type Thread struct {
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// ID of thread.
	ThreadID string `json:"thread_id"`
	// Labels of thread.
	Labels []string `json:"labels"`
	// Timestamp of last sent or received message.
	Timestamp time.Time `json:"timestamp"`
	// Timestamp of last received message.
	ReceivedTimestamp *time.Time `json:"received_timestamp,omitzero"`
	// Timestamp of last sent message.
	SentTimestamp *time.Time `json:"sent_timestamp,omitzero"`
	// Senders in thread. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Senders []string `json:"senders"`
	// Recipients in thread. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Recipients []string `json:"recipients"`
	// Subject of thread.
	Subject *string `json:"subject,omitzero"`
	// Text preview of last message in thread.
	Preview *string `json:"preview,omitzero"`
	// Attachments in thread.
	Attachments []Attachment `json:"attachments,omitzero"`
	// ID of last message in thread.
	LastMessageID string `json:"last_message_id"`
	// Number of messages in thread.
	MessageCount int64 `json:"message_count"`
	// Size of thread in bytes.
	Size int64 `json:"size"`
	// Time at which thread was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Time at which thread was created.
	CreatedAt time.Time `json:"created_at"`
	// Messages in thread. Ordered by `timestamp` ascending.
	Messages []Message `json:"messages"`
}

func (t Thread) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Thread) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Thread) GetInboxID() string {
	if t == nil {
		return ""
	}
	return t.InboxID
}

func (t *Thread) GetThreadID() string {
	if t == nil {
		return ""
	}
	return t.ThreadID
}

func (t *Thread) GetLabels() []string {
	if t == nil {
		return []string{}
	}
	return t.Labels
}

func (t *Thread) GetTimestamp() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.Timestamp
}

func (t *Thread) GetReceivedTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.ReceivedTimestamp
}

func (t *Thread) GetSentTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.SentTimestamp
}

func (t *Thread) GetSenders() []string {
	if t == nil {
		return []string{}
	}
	return t.Senders
}

func (t *Thread) GetRecipients() []string {
	if t == nil {
		return []string{}
	}
	return t.Recipients
}

func (t *Thread) GetSubject() *string {
	if t == nil {
		return nil
	}
	return t.Subject
}

func (t *Thread) GetPreview() *string {
	if t == nil {
		return nil
	}
	return t.Preview
}

func (t *Thread) GetAttachments() []Attachment {
	if t == nil {
		return nil
	}
	return t.Attachments
}

func (t *Thread) GetLastMessageID() string {
	if t == nil {
		return ""
	}
	return t.LastMessageID
}

func (t *Thread) GetMessageCount() int64 {
	if t == nil {
		return 0
	}
	return t.MessageCount
}

func (t *Thread) GetSize() int64 {
	if t == nil {
		return 0
	}
	return t.Size
}

func (t *Thread) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}

func (t *Thread) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *Thread) GetMessages() []Message {
	if t == nil {
		return []Message{}
	}
	return t.Messages
}
