// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type ThreadItem struct {
	// The ID of the inbox.
	InboxID string `json:"inbox_id"`
	// ID of thread.
	ThreadID string `json:"thread_id"`
	// Labels of thread.
	Labels []string `json:"labels"`
	// Timestamp of last sent or received message.
	Timestamp time.Time `json:"timestamp"`
	// Timestamp of last received message.
	ReceivedTimestamp *time.Time `json:"received_timestamp,omitzero"`
	// Timestamp of last sent message.
	SentTimestamp *time.Time `json:"sent_timestamp,omitzero"`
	// Senders in thread. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Senders []string `json:"senders"`
	// Recipients in thread. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Recipients []string `json:"recipients"`
	// Subject of thread.
	Subject *string `json:"subject,omitzero"`
	// Text preview of last message in thread.
	Preview *string `json:"preview,omitzero"`
	// Attachments in thread.
	Attachments []Attachment `json:"attachments,omitzero"`
	// ID of last message in thread.
	LastMessageID string `json:"last_message_id"`
	// Number of messages in thread.
	MessageCount int64 `json:"message_count"`
	// Size of thread in bytes.
	Size int64 `json:"size"`
	// Time at which thread was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Time at which thread was created.
	CreatedAt time.Time `json:"created_at"`
}

func (t ThreadItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ThreadItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ThreadItem) GetInboxID() string {
	if t == nil {
		return ""
	}
	return t.InboxID
}

func (t *ThreadItem) GetThreadID() string {
	if t == nil {
		return ""
	}
	return t.ThreadID
}

func (t *ThreadItem) GetLabels() []string {
	if t == nil {
		return []string{}
	}
	return t.Labels
}

func (t *ThreadItem) GetTimestamp() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.Timestamp
}

func (t *ThreadItem) GetReceivedTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.ReceivedTimestamp
}

func (t *ThreadItem) GetSentTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.SentTimestamp
}

func (t *ThreadItem) GetSenders() []string {
	if t == nil {
		return []string{}
	}
	return t.Senders
}

func (t *ThreadItem) GetRecipients() []string {
	if t == nil {
		return []string{}
	}
	return t.Recipients
}

func (t *ThreadItem) GetSubject() *string {
	if t == nil {
		return nil
	}
	return t.Subject
}

func (t *ThreadItem) GetPreview() *string {
	if t == nil {
		return nil
	}
	return t.Preview
}

func (t *ThreadItem) GetAttachments() []Attachment {
	if t == nil {
		return nil
	}
	return t.Attachments
}

func (t *ThreadItem) GetLastMessageID() string {
	if t == nil {
		return ""
	}
	return t.LastMessageID
}

func (t *ThreadItem) GetMessageCount() int64 {
	if t == nil {
		return 0
	}
	return t.MessageCount
}

func (t *ThreadItem) GetSize() int64 {
	if t == nil {
		return 0
	}
	return t.Size
}

func (t *ThreadItem) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}

func (t *ThreadItem) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}
