// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type UpdateDraftRequest struct {
	// Reply-to addresses. In format `username@domain.com` or `Display Name <username@domain.com>`.
	ReplyTo []string `json:"reply_to,omitzero"`
	// Addresses of recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	To []string `json:"to,omitzero"`
	// Addresses of CC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Cc []string `json:"cc,omitzero"`
	// Addresses of BCC recipients. In format `username@domain.com` or `Display Name <username@domain.com>`.
	Bcc []string `json:"bcc,omitzero"`
	// Subject of draft.
	Subject *string `json:"subject,omitzero"`
	// Plain text body of draft.
	Text *string `json:"text,omitzero"`
	// HTML body of draft.
	HTML *string `json:"html,omitzero"`
	// Time at which to schedule send draft.
	SendAt *time.Time `json:"send_at,omitzero"`
}

func (u UpdateDraftRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateDraftRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateDraftRequest) GetReplyTo() []string {
	if u == nil {
		return nil
	}
	return u.ReplyTo
}

func (u *UpdateDraftRequest) GetTo() []string {
	if u == nil {
		return nil
	}
	return u.To
}

func (u *UpdateDraftRequest) GetCc() []string {
	if u == nil {
		return nil
	}
	return u.Cc
}

func (u *UpdateDraftRequest) GetBcc() []string {
	if u == nil {
		return nil
	}
	return u.Bcc
}

func (u *UpdateDraftRequest) GetSubject() *string {
	if u == nil {
		return nil
	}
	return u.Subject
}

func (u *UpdateDraftRequest) GetText() *string {
	if u == nil {
		return nil
	}
	return u.Text
}

func (u *UpdateDraftRequest) GetHTML() *string {
	if u == nil {
		return nil
	}
	return u.HTML
}

func (u *UpdateDraftRequest) GetSendAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.SendAt
}
