// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/sdkinternal/utils"
	"errors"
	"fmt"
)

type UpdateMessageLabelsType string

const (
	UpdateMessageLabelsTypeStr        UpdateMessageLabelsType = "str"
	UpdateMessageLabelsTypeArrayOfStr UpdateMessageLabelsType = "arrayOfStr"
)

// UpdateMessageLabels - Label or list of labels.
type UpdateMessageLabels struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type UpdateMessageLabelsType
}

func CreateUpdateMessageLabelsStr(str string) UpdateMessageLabels {
	typ := UpdateMessageLabelsTypeStr

	return UpdateMessageLabels{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpdateMessageLabelsArrayOfStr(arrayOfStr []string) UpdateMessageLabels {
	typ := UpdateMessageLabelsTypeArrayOfStr

	return UpdateMessageLabels{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *UpdateMessageLabels) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateMessageLabelsTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateMessageLabelsTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateMessageLabels", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateMessageLabels", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateMessageLabelsType)
	switch best.Type {
	case UpdateMessageLabelsTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case UpdateMessageLabelsTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateMessageLabels", string(data))
}

func (u UpdateMessageLabels) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateMessageLabels: all fields are null")
}
