// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDomainRequest struct {
	// Bounce and complaint notifications are sent to your inboxes.
	FeedbackEnabled *bool `json:"feedback_enabled,omitzero"`
}

func (u *UpdateDomainRequest) GetFeedbackEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.FeedbackEnabled
}
