// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"agentmail-cli/internal/sdk/optionalnullable"
)

type VerificationRecord struct {
	Type RecordType `json:"type"`
	// The name or host of the record.
	Name string `json:"name"`
	// The value of the record.
	Value  string       `json:"value"`
	Status RecordStatus `json:"status"`
	// The priority of the MX record.
	Priority optionalnullable.OptionalNullable[int64] `json:"priority,omitzero"`
}

func (v *VerificationRecord) GetType() RecordType {
	if v == nil {
		return RecordType("")
	}
	return v.Type
}

func (v *VerificationRecord) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VerificationRecord) GetValue() string {
	if v == nil {
		return ""
	}
	return v.Value
}

func (v *VerificationRecord) GetStatus() RecordStatus {
	if v == nil {
		return RecordStatus("")
	}
	return v.Status
}

func (v *VerificationRecord) GetPriority() optionalnullable.OptionalNullable[int64] {
	if v == nil {
		return nil
	}
	return v.Priority
}
