// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package messages

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesMessagesGetRawCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "message-id", Shorthand: "m", FieldPath: "MessageID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initInboxesMessagesGetRawCmd initializes the inboxes-messages-get-raw command.
func initInboxesMessagesGetRawCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "inboxes-messages-get-raw",
		Short:   "Get Raw Message",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:messages get-raw --inbox-id <inbox_id> --message-id <message_id>\n```",
		Example: "  agentmail messages inboxes-messages-get-raw --inbox-id <id> --message-id <id>",
		RunE:    runInboxesMessagesGetRawCmd,
		Aliases: []string{"imgr"},
	}
	flagutil.RegisterFlags(cmd, inboxesMessagesGetRawCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesMessagesGetRawRequest](inboxesMessagesGetRawCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-messages-get-raw: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesMessagesGetRawCmd executes the inboxes-messages-get-raw command.
func runInboxesMessagesGetRawCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesMessagesGetRawCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesMessagesGetRawCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesMessagesGetRawRequest](cmd, inboxesMessagesGetRawCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesMessagesGetRawServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesMessagesGetRawServerList)-1)
		}
		serverURL := operations.InboxesMessagesGetRawServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Messages.InboxesMessagesGetRaw(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
