// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package messages

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesMessagesSendCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", Shorthand: "i", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "labels", Shorthand: "l", FieldPath: "Body.Labels", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Labels of message."},
	{FlagName: "reply-to", Shorthand: "r", FieldPath: "Body.ReplyTo", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "to", FieldPath: "Body.To", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "cc", Shorthand: "c", FieldPath: "Body.Cc", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "bcc", Shorthand: "b", FieldPath: "Body.Bcc", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "subject", Shorthand: "s", FieldPath: "Body.Subject", Kind: flagutil.FlagKindString, Optional: true, Description: "Subject of message."},
	{FlagName: "text", FieldPath: "Body.Text", Kind: flagutil.FlagKindString, Optional: true, Description: "Plain text body of message."},
	{FlagName: "html", FieldPath: "Body.HTML", Kind: flagutil.FlagKindString, Optional: true, Description: "HTML body of message."},
	{FlagName: "attachments", Shorthand: "a", FieldPath: "Body.Attachments", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"attachments,omitempty"`, Description: "Attachments to include in message."},
	{FlagName: "headers", FieldPath: "Body.Headers", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"headers,omitempty"`, Description: "Headers to include in message."},
}

// initInboxesMessagesSendCmd initializes the inboxes-messages-send command.
func initInboxesMessagesSendCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "inboxes-messages-send",
		Short:   "Send Message",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:messages send --inbox-id <inbox_id> --to recipient@example.com --subject \"Hello\" --text \"Body\"\n```",
		Example: "  agentmail messages inboxes-messages-send --inbox-id <id>",
		RunE:    runInboxesMessagesSendCmd,
		Aliases: []string{"ims"},
	}
	flagutil.RegisterFlags(cmd, inboxesMessagesSendCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesMessagesSendRequest](inboxesMessagesSendCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-messages-send: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runInboxesMessagesSendCmd executes the inboxes-messages-send command.
func runInboxesMessagesSendCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesMessagesSendCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesMessagesSendCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesMessagesSendRequest](cmd, inboxesMessagesSendCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesMessagesSendServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesMessagesSendServerList)-1)
		}
		serverURL := operations.InboxesMessagesSendServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Messages.InboxesMessagesSend(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
