// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package messages

import (
	"agentmail-cli/internal/client"
	"agentmail-cli/internal/flagutil"
	"agentmail-cli/internal/interactive"
	"agentmail-cli/internal/output"
	"agentmail-cli/internal/sdk/models/operations"
	"agentmail-cli/internal/usage"
	"fmt"
	"github.com/spf13/cobra"
	"strconv"
)

var inboxesMessagesListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "inbox-id", FieldPath: "InboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "limit", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "page-token", Shorthand: "p", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "labels", FieldPath: "Labels", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
	{FlagName: "before", Shorthand: "b", FieldPath: "Before", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "after", FieldPath: "After", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "ascending", FieldPath: "Ascending", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "include-spam", FieldPath: "IncludeSpam", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "include-blocked", FieldPath: "IncludeBlocked", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "include-trash", FieldPath: "IncludeTrash", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initInboxesMessagesListCmd initializes the inboxes-messages-list command.
func initInboxesMessagesListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "inboxes-messages-list",
		Short:   "List Messages",
		Long:    "**CLI:**\n```bash\nagentmail inboxes:messages list --inbox-id <inbox_id>\n```",
		Example: "  agentmail messages inboxes-messages-list --inbox-id <id>",
		RunE:    runInboxesMessagesListCmd,
		Aliases: []string{"iml"},
	}
	flagutil.RegisterFlags(cmd, inboxesMessagesListCmdMeta)
	if err := flagutil.ValidateMeta[operations.InboxesMessagesListRequest](inboxesMessagesListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for inboxes-messages-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runInboxesMessagesListCmd executes the inboxes-messages-list command.
func runInboxesMessagesListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, inboxesMessagesListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, inboxesMessagesListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.InboxesMessagesListRequest](cmd, inboxesMessagesListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		serverIdx, err := strconv.Atoi(serverFlag)
		if err != nil {
			return fmt.Errorf("invalid server index %q: must be an integer", serverFlag)
		}
		if serverIdx < 0 || serverIdx >= len(operations.InboxesMessagesListServerList) {
			return fmt.Errorf("server index %d out of range (0-%d)", serverIdx, len(operations.InboxesMessagesListServerList)-1)
		}
		serverURL := operations.InboxesMessagesListServerList[serverIdx]
		sdkOpts = append(sdkOpts, operations.WithServerURL(serverURL))
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Inboxes.Messages.InboxesMessagesList(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
