// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package messages

import (
	"agentmail-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitMessagesRoot(parent *cobra.Command) error {
	var MessagesCmd = &cobra.Command{
		Use:   "messages",
		Short: "Operations for messages",
		Long:  "Operations for messages",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initInboxesMessagesListCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesGetCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesUpdateCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesDeleteCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesGetAttachmentCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesGetRawCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesSendCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesReplyCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesReplyAllCmd(MessagesCmd); err != nil {
		return err
	}

	if err := initInboxesMessagesForwardCmd(MessagesCmd); err != nil {
		return err
	}

	parent.AddCommand(MessagesCmd)
	return nil
}
